/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdreslerimRouteImport } from './routes/adreslerim'
import { Route as AndroidRouteImport } from './routes/android'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndirRouteImport } from './routes/indir'
import { Route as IphoneRouteImport } from './routes/iphone'
import { Route as KurucuRouteImport } from './routes/kurucu'
import { Route as KurucuGirisRouteImport } from './routes/kurucu-giris'
import { Route as MobilRouteImport } from './routes/mobil'
import { Route as OdemeRouteImport } from './routes/odeme'
import { Route as RestoranlarRouteImport } from './routes/restoranlar'
import { Route as SepetRouteImport } from './routes/sepet'
import { Route as SifreSifirlamaRouteImport } from './routes/sifre-sifirlama'
import { Route as SiparislerimRouteImport } from './routes/siparislerim'
import { Route as SistemHatalariRouteImport } from './routes/sistem-hatalari'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSplatRouteImport } from './routes/admin.$'
import { Route as RestoranSlugRouteImport } from './routes/restoran.$slug'
import { Route as SiparisIdRouteImport } from './routes/siparis.$id'
import { Route as VendorDashboardRouteImport } from './routes/vendor.dashboard'
import { Route as ApiV1BannersRouteImport } from './routes/api/v1/banners'
import { Route as ApiPublicBrandSplatRouteImport } from './routes/api/public/brand.$'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media.$'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as ApiV1BannersIdTrackRouteImport } from './routes/api/v1/banners.$id.track'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdreslerimRoute = AdreslerimRouteImport.update({
  id: '/adreslerim',
  path: '/adreslerim',
  getParentRoute: () => rootRouteImport,
} as any)
const AndroidRoute = AndroidRouteImport.update({
  id: '/android',
  path: '/android',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndirRoute = IndirRouteImport.update({
  id: '/indir',
  path: '/indir',
  getParentRoute: () => rootRouteImport,
} as any)
const IphoneRoute = IphoneRouteImport.update({
  id: '/iphone',
  path: '/iphone',
  getParentRoute: () => rootRouteImport,
} as any)
const KurucuRoute = KurucuRouteImport.update({
  id: '/kurucu',
  path: '/kurucu',
  getParentRoute: () => rootRouteImport,
} as any)
const KurucuGirisRoute = KurucuGirisRouteImport.update({
  id: '/kurucu-giris',
  path: '/kurucu-giris',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilRoute = MobilRouteImport.update({
  id: '/mobil',
  path: '/mobil',
  getParentRoute: () => rootRouteImport,
} as any)
const OdemeRoute = OdemeRouteImport.update({
  id: '/odeme',
  path: '/odeme',
  getParentRoute: () => rootRouteImport,
} as any)
const RestoranlarRoute = RestoranlarRouteImport.update({
  id: '/restoranlar',
  path: '/restoranlar',
  getParentRoute: () => rootRouteImport,
} as any)
const SepetRoute = SepetRouteImport.update({
  id: '/sepet',
  path: '/sepet',
  getParentRoute: () => rootRouteImport,
} as any)
const SifreSifirlamaRoute = SifreSifirlamaRouteImport.update({
  id: '/sifre-sifirlama',
  path: '/sifre-sifirlama',
  getParentRoute: () => rootRouteImport,
} as any)
const SiparislerimRoute = SiparislerimRouteImport.update({
  id: '/siparislerim',
  path: '/siparislerim',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemHatalariRoute = SistemHatalariRouteImport.update({
  id: '/sistem-hatalari',
  path: '/sistem-hatalari',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RestoranSlugRoute = RestoranSlugRouteImport.update({
  id: '/restoran/$slug',
  path: '/restoran/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SiparisIdRoute = SiparisIdRouteImport.update({
  id: '/siparis/$id',
  path: '/siparis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BannersRoute = ApiV1BannersRouteImport.update({
  id: '/api/v1/banners',
  path: '/api/v1/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBrandSplatRoute = ApiPublicBrandSplatRouteImport.update({
  id: '/api/public/brand/$',
  path: '/api/public/brand/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BannersIdTrackRoute = ApiV1BannersIdTrackRouteImport.update({
  id: '/$id/track',
  path: '/$id/track',
  getParentRoute: () => ApiV1BannersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/adreslerim': typeof AdreslerimRoute
  '/android': typeof AndroidRoute
  '/auth': typeof AuthRoute
  '/indir': typeof IndirRoute
  '/iphone': typeof IphoneRoute
  '/kurucu': typeof KurucuRoute
  '/kurucu-giris': typeof KurucuGirisRoute
  '/mobil': typeof MobilRoute
  '/odeme': typeof OdemeRoute
  '/restoranlar': typeof RestoranlarRoute
  '/sepet': typeof SepetRoute
  '/sifre-sifirlama': typeof SifreSifirlamaRoute
  '/siparislerim': typeof SiparislerimRoute
  '/sistem-hatalari': typeof SistemHatalariRoute
  '/admin/$': typeof AdminSplatRoute
  '/restoran/$slug': typeof RestoranSlugRoute
  '/siparis/$id': typeof SiparisIdRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/api/v1/banners': typeof ApiV1BannersRouteWithChildren
  '/api/public/brand/$': typeof ApiPublicBrandSplatRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/api/v1/banners/$id/track': typeof ApiV1BannersIdTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/adreslerim': typeof AdreslerimRoute
  '/android': typeof AndroidRoute
  '/auth': typeof AuthRoute
  '/indir': typeof IndirRoute
  '/iphone': typeof IphoneRoute
  '/kurucu': typeof KurucuRoute
  '/kurucu-giris': typeof KurucuGirisRoute
  '/mobil': typeof MobilRoute
  '/odeme': typeof OdemeRoute
  '/restoranlar': typeof RestoranlarRoute
  '/sepet': typeof SepetRoute
  '/sifre-sifirlama': typeof SifreSifirlamaRoute
  '/siparislerim': typeof SiparislerimRoute
  '/sistem-hatalari': typeof SistemHatalariRoute
  '/admin/$': typeof AdminSplatRoute
  '/restoran/$slug': typeof RestoranSlugRoute
  '/siparis/$id': typeof SiparisIdRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/api/v1/banners': typeof ApiV1BannersRouteWithChildren
  '/api/public/brand/$': typeof ApiPublicBrandSplatRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/api/v1/banners/$id/track': typeof ApiV1BannersIdTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/adreslerim': typeof AdreslerimRoute
  '/android': typeof AndroidRoute
  '/auth': typeof AuthRoute
  '/indir': typeof IndirRoute
  '/iphone': typeof IphoneRoute
  '/kurucu': typeof KurucuRoute
  '/kurucu-giris': typeof KurucuGirisRoute
  '/mobil': typeof MobilRoute
  '/odeme': typeof OdemeRoute
  '/restoranlar': typeof RestoranlarRoute
  '/sepet': typeof SepetRoute
  '/sifre-sifirlama': typeof SifreSifirlamaRoute
  '/siparislerim': typeof SiparislerimRoute
  '/sistem-hatalari': typeof SistemHatalariRoute
  '/admin/$': typeof AdminSplatRoute
  '/restoran/$slug': typeof RestoranSlugRoute
  '/siparis/$id': typeof SiparisIdRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/api/v1/banners': typeof ApiV1BannersRouteWithChildren
  '/api/public/brand/$': typeof ApiPublicBrandSplatRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/api/v1/banners/$id/track': typeof ApiV1BannersIdTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/adreslerim'
    | '/android'
    | '/auth'
    | '/indir'
    | '/iphone'
    | '/kurucu'
    | '/kurucu-giris'
    | '/mobil'
    | '/odeme'
    | '/restoranlar'
    | '/sepet'
    | '/sifre-sifirlama'
    | '/siparislerim'
    | '/sistem-hatalari'
    | '/admin/$'
    | '/restoran/$slug'
    | '/siparis/$id'
    | '/vendor/dashboard'
    | '/admin/'
    | '/api/v1/banners'
    | '/api/public/brand/$'
    | '/api/public/media/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/api/v1/banners/$id/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/adreslerim'
    | '/android'
    | '/auth'
    | '/indir'
    | '/iphone'
    | '/kurucu'
    | '/kurucu-giris'
    | '/mobil'
    | '/odeme'
    | '/restoranlar'
    | '/sepet'
    | '/sifre-sifirlama'
    | '/siparislerim'
    | '/sistem-hatalari'
    | '/admin/$'
    | '/restoran/$slug'
    | '/siparis/$id'
    | '/vendor/dashboard'
    | '/admin'
    | '/api/v1/banners'
    | '/api/public/brand/$'
    | '/api/public/media/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/api/v1/banners/$id/track'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/adreslerim'
    | '/android'
    | '/auth'
    | '/indir'
    | '/iphone'
    | '/kurucu'
    | '/kurucu-giris'
    | '/mobil'
    | '/odeme'
    | '/restoranlar'
    | '/sepet'
    | '/sifre-sifirlama'
    | '/siparislerim'
    | '/sistem-hatalari'
    | '/admin/$'
    | '/restoran/$slug'
    | '/siparis/$id'
    | '/vendor/dashboard'
    | '/admin/'
    | '/api/v1/banners'
    | '/api/public/brand/$'
    | '/api/public/media/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/api/v1/banners/$id/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdreslerimRoute: typeof AdreslerimRoute
  AndroidRoute: typeof AndroidRoute
  AuthRoute: typeof AuthRoute
  IndirRoute: typeof IndirRoute
  IphoneRoute: typeof IphoneRoute
  KurucuRoute: typeof KurucuRoute
  KurucuGirisRoute: typeof KurucuGirisRoute
  MobilRoute: typeof MobilRoute
  OdemeRoute: typeof OdemeRoute
  RestoranlarRoute: typeof RestoranlarRoute
  SepetRoute: typeof SepetRoute
  SifreSifirlamaRoute: typeof SifreSifirlamaRoute
  SiparislerimRoute: typeof SiparislerimRoute
  SistemHatalariRoute: typeof SistemHatalariRoute
  AdminSplatRoute: typeof AdminSplatRoute
  RestoranSlugRoute: typeof RestoranSlugRoute
  SiparisIdRoute: typeof SiparisIdRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiV1BannersRoute: typeof ApiV1BannersRouteWithChildren
  ApiPublicBrandSplatRoute: typeof ApiPublicBrandSplatRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adreslerim': {
      id: '/adreslerim'
      path: '/adreslerim'
      fullPath: '/adreslerim'
      preLoaderRoute: typeof AdreslerimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/android': {
      id: '/android'
      path: '/android'
      fullPath: '/android'
      preLoaderRoute: typeof AndroidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indir': {
      id: '/indir'
      path: '/indir'
      fullPath: '/indir'
      preLoaderRoute: typeof IndirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iphone': {
      id: '/iphone'
      path: '/iphone'
      fullPath: '/iphone'
      preLoaderRoute: typeof IphoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurucu': {
      id: '/kurucu'
      path: '/kurucu'
      fullPath: '/kurucu'
      preLoaderRoute: typeof KurucuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurucu-giris': {
      id: '/kurucu-giris'
      path: '/kurucu-giris'
      fullPath: '/kurucu-giris'
      preLoaderRoute: typeof KurucuGirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobil': {
      id: '/mobil'
      path: '/mobil'
      fullPath: '/mobil'
      preLoaderRoute: typeof MobilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odeme': {
      id: '/odeme'
      path: '/odeme'
      fullPath: '/odeme'
      preLoaderRoute: typeof OdemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restoranlar': {
      id: '/restoranlar'
      path: '/restoranlar'
      fullPath: '/restoranlar'
      preLoaderRoute: typeof RestoranlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sepet': {
      id: '/sepet'
      path: '/sepet'
      fullPath: '/sepet'
      preLoaderRoute: typeof SepetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sifre-sifirlama': {
      id: '/sifre-sifirlama'
      path: '/sifre-sifirlama'
      fullPath: '/sifre-sifirlama'
      preLoaderRoute: typeof SifreSifirlamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siparislerim': {
      id: '/siparislerim'
      path: '/siparislerim'
      fullPath: '/siparislerim'
      preLoaderRoute: typeof SiparislerimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistem-hatalari': {
      id: '/sistem-hatalari'
      path: '/sistem-hatalari'
      fullPath: '/sistem-hatalari'
      preLoaderRoute: typeof SistemHatalariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restoran/$slug': {
      id: '/restoran/$slug'
      path: '/restoran/$slug'
      fullPath: '/restoran/$slug'
      preLoaderRoute: typeof RestoranSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siparis/$id': {
      id: '/siparis/$id'
      path: '/siparis/$id'
      fullPath: '/siparis/$id'
      preLoaderRoute: typeof SiparisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/banners': {
      id: '/api/v1/banners'
      path: '/api/v1/banners'
      fullPath: '/api/v1/banners'
      preLoaderRoute: typeof ApiV1BannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/brand/$': {
      id: '/api/public/brand/$'
      path: '/api/public/brand/$'
      fullPath: '/api/public/brand/$'
      preLoaderRoute: typeof ApiPublicBrandSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/banners/$id/track': {
      id: '/api/v1/banners/$id/track'
      path: '/$id/track'
      fullPath: '/api/v1/banners/$id/track'
      preLoaderRoute: typeof ApiV1BannersIdTrackRouteImport
      parentRoute: typeof ApiV1BannersRoute
    }
  }
}

interface ApiV1BannersRouteChildren {
  ApiV1BannersIdTrackRoute: typeof ApiV1BannersIdTrackRoute
}

const ApiV1BannersRouteChildren: ApiV1BannersRouteChildren = {
  ApiV1BannersIdTrackRoute: ApiV1BannersIdTrackRoute,
}

const ApiV1BannersRouteWithChildren = ApiV1BannersRoute._addFileChildren(
  ApiV1BannersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdreslerimRoute: AdreslerimRoute,
  AndroidRoute: AndroidRoute,
  AuthRoute: AuthRoute,
  IndirRoute: IndirRoute,
  IphoneRoute: IphoneRoute,
  KurucuRoute: KurucuRoute,
  KurucuGirisRoute: KurucuGirisRoute,
  MobilRoute: MobilRoute,
  OdemeRoute: OdemeRoute,
  RestoranlarRoute: RestoranlarRoute,
  SepetRoute: SepetRoute,
  SifreSifirlamaRoute: SifreSifirlamaRoute,
  SiparislerimRoute: SiparislerimRoute,
  SistemHatalariRoute: SistemHatalariRoute,
  AdminSplatRoute: AdminSplatRoute,
  RestoranSlugRoute: RestoranSlugRoute,
  SiparisIdRoute: SiparisIdRoute,
  VendorDashboardRoute: VendorDashboardRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiV1BannersRoute: ApiV1BannersRouteWithChildren,
  ApiPublicBrandSplatRoute: ApiPublicBrandSplatRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
