/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestoranlarRouteImport } from './routes/restoranlar'
import { Route as RestoranSlugRouteImport } from './routes/restoran.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestoranlarRoute = RestoranlarRouteImport.update({
  id: '/restoranlar',
  path: '/restoranlar',
  getParentRoute: () => rootRouteImport,
} as any)
const RestoranSlugRoute = RestoranSlugRouteImport.update({
  id: '/restoran/$slug',
  path: '/restoran/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/restoranlar': typeof RestoranlarRoute
  '/restoran/$slug': typeof RestoranSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/restoranlar': typeof RestoranlarRoute
  '/restoran/$slug': typeof RestoranSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/restoranlar': typeof RestoranlarRoute
  '/restoran/$slug': typeof RestoranSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/restoranlar' | '/restoran/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/restoranlar' | '/restoran/$slug'
  id: '__root__' | '/' | '/restoranlar' | '/restoran/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RestoranlarRoute: typeof RestoranlarRoute
  RestoranSlugRoute: typeof RestoranSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restoranlar': {
      id: '/restoranlar'
      path: '/restoranlar'
      fullPath: '/restoranlar'
      preLoaderRoute: typeof RestoranlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restoran/$slug': {
      id: '/restoran/$slug'
      path: '/restoran/$slug'
      fullPath: '/restoran/$slug'
      preLoaderRoute: typeof RestoranSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RestoranlarRoute: RestoranlarRoute,
  RestoranSlugRoute: RestoranSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
