-- İşletme kategori kataloğu: işletme başvurusu ve Sayfa Yöneticisi Paneli'ndeki
-- "Alt tür" arama motorunun ortak kaynağı. Mevcut 14 ana kategoriye
-- (app_categories) DOKUNMAZ; her satır isteğe bağlı olarak birine bağlanır
-- (sector_slug). Seçilen ad restaurants.category'ye yazılır; oradaki eski
-- serbest metinler geçerli kalır.
--
-- Bu dosya scripts/gen-business-category-seed.ts ile üretildi.

CREATE TABLE IF NOT EXISTS public.business_category_catalog (
  slug text PRIMARY KEY CHECK (slug ~ '^[a-z0-9-]+$' AND length(slug) <= 60),
  name text NOT NULL CHECK (length(name) BETWEEN 2 AND 40),
  group_name text NOT NULL CHECK (length(group_name) BETWEEN 2 AND 60),
  sector_slug text CHECK (sector_slug IS NULL OR sector_slug ~ '^[a-z0-9-]+$'),
  synonyms text[] NOT NULL DEFAULT '{}'::text[],
  position integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.business_category_catalog ENABLE ROW LEVEL SECURITY;

-- Herkes okuyabilir (başvuru formu giriş yapmadan da açılabiliyor); yazma
-- yalnız servis rolüyle (göç / sunucu). Tarayıcıdan ekleme-silme yok.
DROP POLICY IF EXISTS business_category_catalog_public_read ON public.business_category_catalog;
CREATE POLICY business_category_catalog_public_read
  ON public.business_category_catalog
  FOR SELECT
  TO anon, authenticated
  USING (is_active);

REVOKE ALL ON public.business_category_catalog FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.business_category_catalog TO anon, authenticated;
GRANT ALL ON public.business_category_catalog TO service_role;

INSERT INTO public.business_category_catalog (slug, name, group_name, sector_slug, synonyms, position)
VALUES
  ('restoran', 'Restoran', 'Yeme-İçme', 'restoran', ARRAY['lokanta', 'bistro', 'aile restoranı', 'yemek salonu']::text[], 1),
  ('ev-yemekleri', 'Ev yemekleri', 'Yeme-İçme', 'yemek', ARRAY['esnaf lokantası', 'sulu yemek', 'tabldot', 'hazır yemek']::text[], 2),
  ('kebapci', 'Kebapçı', 'Yeme-İçme', 'restoran', ARRAY['kebap', 'ocakbaşı', 'mangal', 'adana', 'urfa', 'cağ kebabı']::text[], 3),
  ('donerci', 'Dönerci', 'Yeme-İçme', 'yemek', ARRAY['döner', 'et döner', 'tavuk döner', 'iskender']::text[], 4),
  ('pide-ve-lahmacun', 'Pide ve lahmacun', 'Yeme-İçme', 'yemek', ARRAY['pideci', 'lahmacun', 'etli ekmek', 'kıymalı pide']::text[], 5),
  ('pizzaci', 'Pizzacı', 'Yeme-İçme', 'yemek', ARRAY['pizza', 'pizzeria', 'italyan pizza']::text[], 6),
  ('hamburgerci', 'Hamburgerci', 'Yeme-İçme', 'yemek', ARRAY['burger', 'hamburger', 'cheeseburger']::text[], 7),
  ('kofteci', 'Köfteci', 'Yeme-İçme', 'yemek', ARRAY['köfte', 'ızgara köfte', 'piyaz']::text[], 8),
  ('tavukcu', 'Tavukçu', 'Yeme-İçme', 'yemek', ARRAY['tavuk', 'piliç çevirme', 'kanat', 'tavuk şiş']::text[], 9),
  ('balik-restorani', 'Balık restoranı', 'Yeme-İçme', 'restoran', ARRAY['balık', 'deniz ürünleri', 'balık ekmek', 'kalamar']::text[], 10),
  ('cig-kofteci', 'Çiğ köfteci', 'Yeme-İçme', 'yemek', ARRAY['çiğköfte', 'çiğ köfte dürüm']::text[], 11),
  ('kokorecci', 'Kokoreççi', 'Yeme-İçme', 'yemek', ARRAY['kokoreç', 'uykuluk']::text[], 12),
  ('tantuni', 'Tantuni', 'Yeme-İçme', 'yemek', ARRAY['tantunici', 'tantuni dürüm']::text[], 13),
  ('durumcu', 'Dürümcü', 'Yeme-İçme', 'yemek', ARRAY['dürüm', 'wrap', 'lavaş']::text[], 14),
  ('cigerci', 'Ciğerci', 'Yeme-İçme', 'yemek', ARRAY['ciğer', 'ciğer şiş', 'arnavut ciğeri']::text[], 15),
  ('tandir-ve-kuzu-cevirme', 'Tandır ve kuzu çevirme', 'Yeme-İçme', 'restoran', ARRAY['tandır', 'kuzu çevirme', 'büryan']::text[], 16),
  ('et-restorani', 'Et restoranı', 'Yeme-İçme', 'restoran', ARRAY['steakhouse', 'biftek', 'antrikot', 'et lokantası']::text[], 17),
  ('manti-evi', 'Mantı evi', 'Yeme-İçme', 'yemek', ARRAY['mantı', 'kayseri mantısı']::text[], 18),
  ('gozlemeci', 'Gözlemeci', 'Yeme-İçme', 'yemek', ARRAY['gözleme', 'sac böreği', 'bazlama']::text[], 19),
  ('corbaci', 'Çorbacı', 'Yeme-İçme', 'yemek', ARRAY['çorba', 'işkembe', 'kelle paça', 'mercimek çorbası']::text[], 20),
  ('pilavci', 'Pilavcı', 'Yeme-İçme', 'yemek', ARRAY['nohutlu pilav', 'pilav üstü', 'tavuklu pilav']::text[], 21),
  ('kahvalti-salonu', 'Kahvaltı salonu', 'Yeme-İçme', 'kafe', ARRAY['kahvaltıcı', 'serpme kahvaltı', 'brunch']::text[], 22),
  ('bufe-ve-tostcu', 'Büfe ve tostçu', 'Yeme-İçme', 'yemek', ARRAY['büfe', 'tost', 'sandviç', 'ayvalık tostu', 'sucuk ekmek']::text[], 23),
  ('midyeci', 'Midyeci', 'Yeme-İçme', 'yemek', ARRAY['midye dolma', 'midye tava']::text[], 24),
  ('yoresel-mutfak', 'Yöresel mutfak', 'Yeme-İçme', 'restoran', ARRAY['yöresel yemek', 'kaburga dolması', 'meftune', 'yöre yemekleri']::text[], 25),
  ('uzak-dogu-mutfagi', 'Uzak Doğu mutfağı', 'Yeme-İçme', 'restoran', ARRAY['sushi', 'çin yemeği', 'japon', 'noodle', 'wok']::text[], 26),
  ('dunya-mutfagi', 'Dünya mutfağı', 'Yeme-İçme', 'restoran', ARRAY['italyan', 'meksika', 'makarna', 'fusion']::text[], 27),
  ('vegan-ve-vejetaryen', 'Vegan ve vejetaryen', 'Yeme-İçme', 'restoran', ARRAY['vegan', 'vejetaryen', 'bitkisel yemek']::text[], 28),
  ('saglikli-ve-fit-yemek', 'Sağlıklı ve fit yemek', 'Yeme-İçme', 'yemek', ARRAY['diyet yemek', 'fit menü', 'salata bar', 'bowl']::text[], 29),
  ('catering-ve-toplu-yemek', 'Catering ve toplu yemek', 'Yeme-İçme', 'yemek', ARRAY['yemek firması', 'tabldot servisi', 'organizasyon yemeği']::text[], 30),
  ('meyhane', 'Meyhane', 'Yeme-İçme', 'restoran', ARRAY['rakı', 'meze', 'fasıl']::text[], 31),
  ('bar-ve-pub', 'Bar ve pub', 'Yeme-İçme', 'eglence', ARRAY['bar', 'pub', 'bira', 'kokteyl']::text[], 32),
  ('kafe', 'Kafe', 'Yeme-İçme', 'kafe', ARRAY['kafeterya', 'cafe', 'kafe restoran']::text[], 33),
  ('kahveci', 'Kahveci', 'Yeme-İçme', 'kafe', ARRAY['kahve', 'kahve dükkanı', 'espresso', 'türk kahvesi', '3. nesil kahve']::text[], 34),
  ('cay-bahcesi', 'Çay bahçesi', 'Yeme-İçme', 'kafe', ARRAY['çay ocağı', 'çaycı', 'semaver']::text[], 35),
  ('kahvehane', 'Kahvehane', 'Yeme-İçme', 'kafe', ARRAY['kıraathane', 'okey salonu', 'kahve ocağı']::text[], 36),
  ('nargile-kafe', 'Nargile kafe', 'Yeme-İçme', 'kafe', ARRAY['nargile', 'nargileci']::text[], 37),
  ('meyve-suyu-ve-smoothie', 'Meyve suyu ve smoothie', 'Yeme-İçme', 'kafe', ARRAY['taze sıkma', 'smoothie', 'bubble tea', 'milkshake']::text[], 38),
  ('waffle-ve-kumpir', 'Waffle ve kumpir', 'Yeme-İçme', 'kafe', ARRAY['waffle', 'kumpir', 'krep']::text[], 39),
  ('firin', 'Fırın', 'Fırın, Pastane ve Tatlı', 'market', ARRAY['ekmek fırını', 'ekmekçi', 'somun', 'taş fırın']::text[], 40),
  ('simitci', 'Simitçi', 'Fırın, Pastane ve Tatlı', 'market', ARRAY['simit', 'açma', 'çatal', 'çörek']::text[], 41),
  ('borekci', 'Börekçi', 'Fırın, Pastane ve Tatlı', 'market', ARRAY['börek', 'su böreği', 'kol böreği', 'poğaça']::text[], 42),
  ('pastane', 'Pastane', 'Fırın, Pastane ve Tatlı', 'kafe', ARRAY['pasta', 'yaş pasta', 'kek', 'kurabiye', 'pastacı']::text[], 43),
  ('butik-pasta', 'Butik pasta', 'Fırın, Pastane ve Tatlı', 'kafe', ARRAY['doğum günü pastası', 'özel tasarım pasta', 'cupcake', 'pasta siparişi']::text[], 44),
  ('baklavaci', 'Baklavacı', 'Fırın, Pastane ve Tatlı', 'kafe', ARRAY['baklava', 'şöbiyet', 'antep baklavası', 'fıstıklı']::text[], 45),
  ('kunefeci', 'Künefeci', 'Fırın, Pastane ve Tatlı', 'kafe', ARRAY['künefe', 'katmer', 'hatay künefesi']::text[], 46),
  ('sutlu-tatlici', 'Sütlü tatlıcı', 'Fırın, Pastane ve Tatlı', 'kafe', ARRAY['muhallebici', 'sütlaç', 'kazandibi', 'tavuk göğsü']::text[], 47),
  ('tatlici', 'Tatlıcı', 'Fırın, Pastane ve Tatlı', 'kafe', ARRAY['şerbetli tatlı', 'lokma', 'tulumba', 'kadayıf']::text[], 48),
  ('dondurmaci', 'Dondurmacı', 'Fırın, Pastane ve Tatlı', 'kafe', ARRAY['dondurma', 'maraş dondurması', 'gelato']::text[], 49),
  ('cikolataci', 'Çikolatacı', 'Fırın, Pastane ve Tatlı', 'kafe', ARRAY['çikolata', 'pralin', 'çikolata butiği']::text[], 50),
  ('lokumcu-ve-sekerci', 'Lokumcu ve şekerci', 'Fırın, Pastane ve Tatlı', 'market', ARRAY['lokum', 'akide', 'pişmaniye', 'şekerleme', 'cezerye']::text[], 51),
  ('market', 'Market', 'Market ve Gıda', 'market', ARRAY['mini market', 'gıda market', 'şarküteri market']::text[], 52),
  ('supermarket', 'Süpermarket', 'Market ve Gıda', 'market', ARRAY['zincir market', 'hipermarket', 'büyük market']::text[], 53),
  ('bakkal', 'Bakkal', 'Market ve Gıda', 'market', ARRAY['mahalle bakkalı', 'bakkaliye']::text[], 54),
  ('tekel-bayi', 'Tekel bayi', 'Market ve Gıda', 'market', ARRAY['tekel', 'sigara', 'içki', 'alkol']::text[], 55),
  ('sarkuteri', 'Şarküteri', 'Market ve Gıda', 'market', ARRAY['peynir', 'zeytin', 'sucuk', 'pastırma', 'peynirci']::text[], 56),
  ('kasap', 'Kasap', 'Market ve Gıda', 'market', ARRAY['et', 'kıyma', 'dana eti', 'kuzu eti', 'kasap dükkanı']::text[], 57),
  ('tavuk-eti-satisi', 'Tavuk eti satışı', 'Market ve Gıda', 'market', ARRAY['piliç', 'beyaz et', 'tavuk göğsü', 'but']::text[], 58),
  ('balikci', 'Balıkçı', 'Market ve Gıda', 'market', ARRAY['taze balık', 'balık hali', 'deniz ürünleri satışı']::text[], 59),
  ('manav', 'Manav', 'Market ve Gıda', 'market', ARRAY['meyve', 'sebze', 'yeşillik', 'meyve sebze']::text[], 60),
  ('kuruyemisci', 'Kuruyemişçi', 'Market ve Gıda', 'market', ARRAY['kuruyemiş', 'çekirdek', 'fındık', 'fıstık', 'leblebi']::text[], 61),
  ('aktar', 'Aktar', 'Market ve Gıda', 'market', ARRAY['baharat', 'baharatçı', 'bitki çayı', 'şifalı bitki']::text[], 62),
  ('kahve-ve-cay-dukkani', 'Kahve ve çay dükkanı', 'Market ve Gıda', 'market', ARRAY['çekirdek kahve', 'türk kahvesi satışı', 'çay satışı']::text[], 63),
  ('sut-urunleri', 'Süt ürünleri', 'Market ve Gıda', 'market', ARRAY['süt', 'yoğurt', 'ayran', 'tereyağı', 'mandıra ürünleri']::text[], 64),
  ('dogal-ve-koy-urunleri', 'Doğal ve köy ürünleri', 'Market ve Gıda', 'market', ARRAY['organik', 'köy yumurtası', 'yöresel ürünler', 'doğal ürün']::text[], 65),
  ('ev-yapimi-urunler', 'Ev yapımı ürünler', 'Market ve Gıda', 'market', ARRAY['el emeği', 'tarhana', 'erişte', 'salça', 'reçel']::text[], 66),
  ('bal-ve-ari-urunleri', 'Bal ve arı ürünleri', 'Market ve Gıda', 'market', ARRAY['bal', 'polen', 'propolis', 'arı sütü', 'petek bal']::text[], 67),
  ('zeytin-ve-zeytinyagi', 'Zeytin ve zeytinyağı', 'Market ve Gıda', 'market', ARRAY['zeytinyağı', 'sızma', 'zeytin satışı']::text[], 68),
  ('bakliyat-ve-kuru-gida', 'Bakliyat ve kuru gıda', 'Market ve Gıda', 'market', ARRAY['bakliyat', 'bulgur', 'mercimek', 'pirinç', 'nohut']::text[], 69),
  ('tursucu', 'Turşucu', 'Market ve Gıda', 'market', ARRAY['turşu', 'turşu suyu']::text[], 70),
  ('mezeci', 'Mezeci', 'Market ve Gıda', 'market', ARRAY['meze', 'hazır meze', 'zeytinyağlılar']::text[], 71),
  ('yumurtaci', 'Yumurtacı', 'Market ve Gıda', 'market', ARRAY['yumurta', 'yumurta satışı']::text[], 72),
  ('dondurulmus-gida', 'Dondurulmuş gıda', 'Market ve Gıda', 'market', ARRAY['frozen', 'donuk ürün', 'dondurulmuş sebze']::text[], 73),
  ('glutensiz-ve-diyet-urunler', 'Glutensiz ve diyet ürünler', 'Market ve Gıda', 'market', ARRAY['glutensiz', 'diyabetik', 'şekersiz', 'çölyak']::text[], 74),
  ('su-bayii', 'Su bayii', 'Market ve Gıda', 'market', ARRAY['damacana', 'içme suyu', 'su servisi', 'pet su']::text[], 75),
  ('icecek-bayii', 'İçecek bayii', 'Market ve Gıda', 'market', ARRAY['meşrubat', 'soda', 'maden suyu', 'gazlı içecek']::text[], 76),
  ('toptan-gida', 'Toptan gıda', 'Market ve Gıda', 'market', ARRAY['gıda toptancısı', 'toptancı', 'toptan satış']::text[], 77),
  ('temizlik-urunleri', 'Temizlik ürünleri', 'Market ve Gıda', 'market', ARRAY['deterjan', 'temizlik malzemesi', 'hijyen ürünleri', 'kâğıt ürünler']::text[], 78),
  ('kadin-giyim', 'Kadın giyim', 'Giyim ve Moda', 'giyim', ARRAY['bayan giyim', 'elbise', 'bluz', 'etek']::text[], 79),
  ('erkek-giyim', 'Erkek giyim', 'Giyim ve Moda', 'giyim', ARRAY['gömlek', 'pantolon', 'takım elbise', 'damatlık']::text[], 80),
  ('cocuk-ve-bebek-giyim', 'Çocuk ve bebek giyim', 'Giyim ve Moda', 'giyim', ARRAY['çocuk kıyafeti', 'bebek kıyafeti', 'zıbın']::text[], 81),
  ('tesettur-giyim', 'Tesettür giyim', 'Giyim ve Moda', 'giyim', ARRAY['tesettür', 'eşarp', 'şal', 'ferace', 'pardesü']::text[], 82),
  ('abiye-ve-gece-elbisesi', 'Abiye ve gece elbisesi', 'Giyim ve Moda', 'giyim', ARRAY['abiye', 'nişan elbisesi', 'kına elbisesi']::text[], 83),
  ('spor-giyim', 'Spor giyim', 'Giyim ve Moda', 'giyim', ARRAY['eşofman', 'spor kıyafet', 'tayt']::text[], 84),
  ('ic-giyim', 'İç giyim', 'Giyim ve Moda', 'giyim', ARRAY['iç çamaşırı', 'pijama', 'gecelik', 'çamaşır']::text[], 85),
  ('kot-ve-jean', 'Kot ve jean', 'Giyim ve Moda', 'giyim', ARRAY['kot pantolon', 'denim', 'jean']::text[], 86),
  ('buyuk-beden-giyim', 'Büyük beden giyim', 'Giyim ve Moda', 'giyim', ARRAY['battal beden', 'büyük beden']::text[], 87),
  ('ikinci-el-giyim', 'İkinci el giyim', 'Giyim ve Moda', 'giyim', ARRAY['vintage', 'spot giyim', 'ikinci el kıyafet']::text[], 88),
  ('toptan-giyim', 'Toptan giyim', 'Giyim ve Moda', 'giyim', ARRAY['tekstil toptan', 'konfeksiyon toptan']::text[], 89),
  ('is-elbisesi-ve-uniforma', 'İş elbisesi ve üniforma', 'Giyim ve Moda', 'giyim', ARRAY['iş kıyafeti', 'üniforma', 'önlük', 'okul forması']::text[], 90),
  ('deri-ve-kurk', 'Deri ve kürk', 'Giyim ve Moda', 'giyim', ARRAY['deri ceket', 'deri mont', 'kürk']::text[], 91),
  ('mont-ve-dis-giyim', 'Mont ve dış giyim', 'Giyim ve Moda', 'giyim', ARRAY['mont', 'kaban', 'parka', 'yağmurluk']::text[], 92),
  ('butik', 'Butik', 'Giyim ve Moda', 'giyim', ARRAY['butik mağaza', 'tasarım kıyafet']::text[], 93),
  ('corap-ve-aksesuar', 'Çorap ve aksesuar', 'Giyim ve Moda', 'giyim', ARRAY['çorap', 'kemer', 'cüzdan', 'şapka', 'eldiven']::text[], 94),
  ('kumasci', 'Kumaşçı', 'Giyim ve Moda', 'giyim', ARRAY['kumaş', 'metraj kumaş', 'perdelik kumaş']::text[], 95),
  ('tuhafiye', 'Tuhafiye', 'Giyim ve Moda', 'giyim', ARRAY['düğme', 'fermuar', 'dantel', 'iplik', 'tuhafiyeci']::text[], 96),
  ('terzi', 'Terzi', 'Giyim ve Moda', 'giyim', ARRAY['tadilat', 'paça', 'dikiş', 'elbise dikimi', 'terzihane']::text[], 97),
  ('tekstil-baski-ve-nakis', 'Tekstil baskı ve nakış', 'Giyim ve Moda', 'giyim', ARRAY['nakış', 'tişört baskı', 'logo baskı', 'transfer baskı']::text[], 98),
  ('ayakkabici', 'Ayakkabıcı', 'Ayakkabı, Çanta ve Takı', 'giyim', ARRAY['ayakkabı', 'bot', 'çizme', 'terlik']::text[], 99),
  ('spor-ayakkabi', 'Spor ayakkabı', 'Ayakkabı, Çanta ve Takı', 'giyim', ARRAY['sneaker', 'koşu ayakkabısı']::text[], 100),
  ('canta-ve-valiz', 'Çanta ve valiz', 'Ayakkabı, Çanta ve Takı', 'giyim', ARRAY['çantacı', 'sırt çantası', 'valiz', 'bavul']::text[], 101),
  ('ayakkabi-tamiri', 'Ayakkabı tamiri', 'Ayakkabı, Çanta ve Takı', 'giyim', ARRAY['kunduracı', 'ayakkabı boyacısı', 'pençe']::text[], 102),
  ('kuyumcu', 'Kuyumcu', 'Ayakkabı, Çanta ve Takı', 'giyim', ARRAY['altın', 'gümüş', 'pırlanta', 'bilezik', 'gümüşçü']::text[], 103),
  ('bijuteri', 'Bijuteri', 'Ayakkabı, Çanta ve Takı', 'giyim', ARRAY['takı', 'küpe', 'kolye', 'bileklik']::text[], 104),
  ('saatci', 'Saatçi', 'Ayakkabı, Çanta ve Takı', 'giyim', ARRAY['saat', 'saat tamiri', 'kol saati', 'pil değişimi']::text[], 105),
  ('kadin-kuaforu', 'Kadın kuaförü', 'Güzellik ve Kişisel Bakım', 'sac-bakimi', ARRAY['kuaför', 'bayan kuaför', 'fön', 'röfle', 'saç boyama', 'keratin', 'ombre', 'gelin başı']::text[], 106),
  ('berber', 'Berber', 'Güzellik ve Kişisel Bakım', 'berber', ARRAY['erkek kuaförü', 'tıraş', 'sakal', 'saç kesimi', 'jilet']::text[], 107),
  ('cocuk-kuaforu', 'Çocuk kuaförü', 'Güzellik ve Kişisel Bakım', 'sac-bakimi', ARRAY['çocuk saç kesimi']::text[], 108),
  ('guzellik-salonu', 'Güzellik salonu', 'Güzellik ve Kişisel Bakım', 'kisisel-bakim', ARRAY['cilt bakımı', 'estetik salonu', 'güzellik merkezi']::text[], 109),
  ('lazer-epilasyon', 'Lazer epilasyon', 'Güzellik ve Kişisel Bakım', 'kisisel-bakim', ARRAY['epilasyon', 'ağda', 'ipl', 'tüy alma']::text[], 110),
  ('manikur-ve-pedikur', 'Manikür ve pedikür', 'Güzellik ve Kişisel Bakım', 'kisisel-bakim', ARRAY['tırnak', 'protez tırnak', 'kalıcı oje', 'nail art']::text[], 111),
  ('kirpik-ve-kas', 'Kirpik ve kaş', 'Güzellik ve Kişisel Bakım', 'kisisel-bakim', ARRAY['ipek kirpik', 'kaş laminasyonu', 'kaş dizaynı', 'lifting']::text[], 112),
  ('kalici-makyaj', 'Kalıcı makyaj', 'Güzellik ve Kişisel Bakım', 'kisisel-bakim', ARRAY['microblading', 'dudak renklendirme', 'dipliner']::text[], 113),
  ('makyaj-artisti', 'Makyaj artisti', 'Güzellik ve Kişisel Bakım', 'kisisel-bakim', ARRAY['gelin makyajı', 'profesyonel makyaj', 'makyöz']::text[], 114),
  ('spa-ve-masaj', 'Spa ve masaj', 'Güzellik ve Kişisel Bakım', 'kisisel-bakim', ARRAY['masaj', 'spa', 'sauna', 'buhar odası']::text[], 115),
  ('hamam', 'Hamam', 'Güzellik ve Kişisel Bakım', 'kisisel-bakim', ARRAY['türk hamamı', 'kese köpük']::text[], 116),
  ('solaryum', 'Solaryum', 'Güzellik ve Kişisel Bakım', 'kisisel-bakim', ARRAY['bronzlaşma', 'sprey bronz']::text[], 117),
  ('dovme-ve-piercing', 'Dövme ve piercing', 'Güzellik ve Kişisel Bakım', 'kisisel-bakim', ARRAY['tattoo', 'dövme', 'piercing', 'hızma']::text[], 118),
  ('protez-sac-ve-peruk', 'Protez saç ve peruk', 'Güzellik ve Kişisel Bakım', 'sac-bakimi', ARRAY['peruk', 'saç protezi', 'postiş']::text[], 119),
  ('kozmetik-ve-parfumeri', 'Kozmetik ve parfümeri', 'Güzellik ve Kişisel Bakım', 'kisisel-bakim', ARRAY['kozmetik', 'parfüm', 'makyaj malzemesi', 'cilt bakım ürünleri']::text[], 120),
  ('zayiflama-merkezi', 'Zayıflama merkezi', 'Güzellik ve Kişisel Bakım', 'kisisel-bakim', ARRAY['bölgesel incelme', 'selülit', 'vücut şekillendirme']::text[], 121),
  ('dis-klinigi', 'Diş kliniği', 'Sağlık', NULL, ARRAY['dişçi', 'diş hekimi', 'implant', 'diş beyazlatma', 'ortodonti']::text[], 122),
  ('poliklinik', 'Poliklinik', 'Sağlık', NULL, ARRAY['tıp merkezi', 'muayenehane', 'sağlık merkezi']::text[], 123),
  ('ozel-hastane', 'Özel hastane', 'Sağlık', NULL, ARRAY['hastane', 'acil servis']::text[], 124),
  ('aile-hekimi', 'Aile hekimi', 'Sağlık', NULL, ARRAY['aile sağlığı merkezi', 'asm']::text[], 125),
  ('fizik-tedavi', 'Fizik tedavi', 'Sağlık', NULL, ARRAY['fizyoterapi', 'rehabilitasyon', 'fizyoterapist']::text[], 126),
  ('psikolog', 'Psikolog', 'Sağlık', NULL, ARRAY['psikolojik danışmanlık', 'terapi', 'psikoterapi', 'aile danışmanı']::text[], 127),
  ('diyetisyen', 'Diyetisyen', 'Sağlık', NULL, ARRAY['beslenme uzmanı', 'diyet', 'kilo verme']::text[], 128),
  ('goz-doktoru', 'Göz doktoru', 'Sağlık', NULL, ARRAY['göz kliniği', 'göz muayenesi', 'katarakt']::text[], 129),
  ('kadin-dogum', 'Kadın doğum', 'Sağlık', NULL, ARRAY['jinekolog', 'gebelik takibi', 'kadın hastalıkları']::text[], 130),
  ('cocuk-doktoru', 'Çocuk doktoru', 'Sağlık', NULL, ARRAY['pediatri', 'pediatrist', 'çocuk hastalıkları']::text[], 131),
  ('cildiye', 'Cildiye', 'Sağlık', NULL, ARRAY['dermatolog', 'cilt doktoru', 'dermatoloji']::text[], 132),
  ('kulak-burun-bogaz', 'Kulak burun boğaz', 'Sağlık', NULL, ARRAY['kbb', 'kulak burun boğaz doktoru']::text[], 133),
  ('ortopedi', 'Ortopedi', 'Sağlık', NULL, ARRAY['ortopedist', 'kemik doktoru']::text[], 134),
  ('tahlil-laboratuvari', 'Tahlil laboratuvarı', 'Sağlık', NULL, ARRAY['laboratuvar', 'kan tahlili', 'test merkezi']::text[], 135),
  ('goruntuleme-merkezi', 'Görüntüleme merkezi', 'Sağlık', NULL, ARRAY['röntgen', 'mr', 'tomografi', 'ultrason']::text[], 136),
  ('evde-saglik-hizmeti', 'Evde sağlık hizmeti', 'Sağlık', NULL, ARRAY['evde bakım', 'hemşire', 'evde serum', 'pansuman']::text[], 137),
  ('huzurevi-ve-bakim-merkezi', 'Huzurevi ve bakım merkezi', 'Sağlık', NULL, ARRAY['yaşlı bakımevi', 'bakım evi', 'huzurevi']::text[], 138),
  ('ozel-ambulans', 'Özel ambulans', 'Sağlık', NULL, ARRAY['ambulans', 'hasta nakil']::text[], 139),
  ('isitme-cihazi-merkezi', 'İşitme cihazı merkezi', 'Sağlık', NULL, ARRAY['işitme cihazı', 'kulak cihazı', 'odyometri']::text[], 140),
  ('estetik-klinik', 'Estetik klinik', 'Sağlık', NULL, ARRAY['estetik cerrahi', 'botoks', 'dolgu', 'plastik cerrahi']::text[], 141),
  ('sac-ekim-merkezi', 'Saç ekim merkezi', 'Sağlık', NULL, ARRAY['saç ekimi', 'fue', 'saç ekim kliniği']::text[], 142),
  ('tamamlayici-tip', 'Tamamlayıcı tıp', 'Sağlık', NULL, ARRAY['akupunktur', 'hacamat', 'kupa', 'ozon terapi']::text[], 143),
  ('dil-ve-konusma-terapisti', 'Dil ve konuşma terapisti', 'Sağlık', NULL, ARRAY['konuşma terapisi', 'logoped', 'kekemelik']::text[], 144),
  ('eczane', 'Eczane', 'Eczane ve Medikal', NULL, ARRAY['nöbetçi eczane', 'ilaç', 'eczacı']::text[], 145),
  ('medikal-malzeme', 'Medikal malzeme', 'Eczane ve Medikal', NULL, ARRAY['tıbbi cihaz', 'tansiyon aleti', 'hasta bezi', 'oksijen tüpü']::text[], 146),
  ('optik', 'Optik', 'Eczane ve Medikal', NULL, ARRAY['gözlükçü', 'gözlük', 'lens', 'güneş gözlüğü']::text[], 147),
  ('ortopedik-urunler', 'Ortopedik ürünler', 'Eczane ve Medikal', NULL, ARRAY['ortopedik ayakkabı', 'korse', 'ortez', 'protez']::text[], 148),
  ('sporcu-besini-ve-takviye', 'Sporcu besini ve takviye', 'Eczane ve Medikal', NULL, ARRAY['vitamin', 'gıda takviyesi', 'protein tozu', 'supplement']::text[], 149),
  ('oto-tamir-servisi', 'Oto tamir servisi', 'Otomotiv', NULL, ARRAY['oto tamirci', 'sanayi', 'mekanik', 'motor tamiri', 'araba tamiri']::text[], 150),
  ('oto-elektrikci', 'Oto elektrikçi', 'Otomotiv', NULL, ARRAY['akü', 'marş motoru', 'şarj dinamosu', 'akücü']::text[], 151),
  ('oto-kaporta-ve-boya', 'Oto kaporta ve boya', 'Otomotiv', NULL, ARRAY['kaportacı', 'oto boyacı', 'göçük düzeltme', 'boyasız göçük']::text[], 152),
  ('lastikci', 'Lastikçi', 'Otomotiv', NULL, ARRAY['lastik', 'rot balans', 'jant', 'lastik tamiri']::text[], 153),
  ('oto-yikama', 'Oto yıkama', 'Otomotiv', NULL, ARRAY['araç yıkama', 'araba yıkama', 'iç temizlik', 'detaylı temizlik']::text[], 154),
  ('oto-kuafor', 'Oto kuaför', 'Otomotiv', NULL, ARRAY['pasta cila', 'seramik kaplama', 'ppf', 'oto detaylandırma']::text[], 155),
  ('oto-yedek-parca', 'Oto yedek parça', 'Otomotiv', NULL, ARRAY['yedek parça', 'parçacı', 'oto parça']::text[], 156),
  ('oto-aksesuar', 'Oto aksesuar', 'Otomotiv', NULL, ARRAY['araç aksesuarı', 'paspas', 'oto multimedya', 'oto teyp']::text[], 157),
  ('oto-cam', 'Oto cam', 'Otomotiv', NULL, ARRAY['cam değişimi', 'cam filmi', 'ön cam']::text[], 158),
  ('oto-doseme', 'Oto döşeme', 'Otomotiv', NULL, ARRAY['koltuk kılıfı', 'tavan döşeme', 'araç döşeme']::text[], 159),
  ('egzozcu', 'Egzozcu', 'Otomotiv', NULL, ARRAY['egzoz', 'katalitik konvertör', 'dpf']::text[], 160),
  ('oto-ekspertiz', 'Oto ekspertiz', 'Otomotiv', NULL, ARRAY['ekspertiz', 'araç ekspertizi', 'hasar tespiti']::text[], 161),
  ('oto-galeri', 'Oto galeri', 'Otomotiv', NULL, ARRAY['ikinci el araba', 'araba alım satım', 'galerici']::text[], 162),
  ('yetkili-servis', 'Yetkili servis', 'Otomotiv', NULL, ARRAY['marka servisi', 'garantili servis']::text[], 163),
  ('motosiklet-satis-ve-servis', 'Motosiklet satış ve servis', 'Otomotiv', NULL, ARRAY['motorcu', 'motosiklet tamiri', 'scooter']::text[], 164),
  ('oto-cekici', 'Oto çekici', 'Otomotiv', NULL, ARRAY['çekici', 'yol yardım', 'oto kurtarma']::text[], 165),
  ('lpg-donusum', 'LPG dönüşüm', 'Otomotiv', NULL, ARRAY['otogaz montajı', 'lpg montaj', 'tüp muayene']::text[], 166),
  ('oto-klima', 'Oto klima', 'Otomotiv', NULL, ARRAY['araç kliması', 'klima gazı dolumu']::text[], 167),
  ('dizel-pompa-ve-enjektor', 'Dizel pompa ve enjektör', 'Otomotiv', NULL, ARRAY['enjektörcü', 'dizel pompa', 'mazot pompası']::text[], 168),
  ('sanziman-tamiri', 'Şanzıman tamiri', 'Otomotiv', NULL, ARRAY['şanzımancı', 'vites kutusu', 'otomatik şanzıman']::text[], 169),
  ('oto-radyator', 'Oto radyatör', 'Otomotiv', NULL, ARRAY['radyatörcü', 'radyatör tamiri']::text[], 170),
  ('oto-anahtar-ve-kilit', 'Oto anahtar ve kilit', 'Otomotiv', NULL, ARRAY['araç anahtarı kopyalama', 'immobilizer', 'kumanda']::text[], 171),
  ('agir-vasita-servisi', 'Ağır vasıta servisi', 'Otomotiv', NULL, ARRAY['kamyon tamiri', 'tır servisi', 'otobüs tamiri']::text[], 172),
  ('otopark', 'Otopark', 'Otomotiv', NULL, ARRAY['kapalı otopark', 'açık otopark', 'vale']::text[], 173),
  ('beyaz-esya-servisi', 'Beyaz eşya servisi', 'Teknik Servis ve Onarım', NULL, ARRAY['buzdolabı tamiri', 'çamaşır makinesi tamiri', 'bulaşık makinesi tamiri']::text[], 174),
  ('kombi-servisi', 'Kombi servisi', 'Teknik Servis ve Onarım', 'tesisat', ARRAY['kombi bakımı', 'petek temizliği', 'kombi tamiri']::text[], 175),
  ('klima-servisi', 'Klima servisi', 'Teknik Servis ve Onarım', 'tesisat', ARRAY['klima montajı', 'klima bakımı', 'klima tamiri']::text[], 176),
  ('telefon-tamiri', 'Telefon tamiri', 'Teknik Servis ve Onarım', 'bilisim-ve-teknoloji', ARRAY['ekran değişimi', 'cep telefonu tamiri', 'batarya değişimi']::text[], 177),
  ('bilgisayar-tamiri', 'Bilgisayar tamiri', 'Teknik Servis ve Onarım', 'bilisim-ve-teknoloji', ARRAY['laptop tamiri', 'format', 'bilgisayar servisi']::text[], 178),
  ('elektronik-tamiri', 'Elektronik tamiri', 'Teknik Servis ve Onarım', 'bilisim-ve-teknoloji', ARRAY['televizyon tamiri', 'tv tamiri', 'ses sistemi tamiri']::text[], 179),
  ('kucuk-ev-aletleri-tamiri', 'Küçük ev aletleri tamiri', 'Teknik Servis ve Onarım', NULL, ARRAY['süpürge tamiri', 'ütü tamiri', 'blender tamiri']::text[], 180),
  ('uydu-ve-anten', 'Uydu ve anten', 'Teknik Servis ve Onarım', 'bilisim-ve-teknoloji', ARRAY['çanak anten', 'uydu kurulumu', 'anten montajı']::text[], 181),
  ('guvenlik-kamerasi-ve-alarm', 'Güvenlik kamerası ve alarm', 'Teknik Servis ve Onarım', 'bilisim-ve-teknoloji', ARRAY['kamera sistemi', 'alarm', 'kartlı geçiş']::text[], 182),
  ('asansor-servisi', 'Asansör servisi', 'Teknik Servis ve Onarım', NULL, ARRAY['asansör bakımı', 'asansör montajı']::text[], 183),
  ('jenerator-servisi', 'Jeneratör servisi', 'Teknik Servis ve Onarım', NULL, ARRAY['jeneratör', 'jeneratör bakımı', 'kesintisiz güç', 'ups']::text[], 184),
  ('yazici-ve-toner', 'Yazıcı ve toner', 'Teknik Servis ve Onarım', 'bilisim-ve-teknoloji', ARRAY['toner dolumu', 'kartuş', 'fotokopi makinesi servisi']::text[], 185),
  ('su-aritma-servisi', 'Su arıtma servisi', 'Teknik Servis ve Onarım', 'tesisat', ARRAY['arıtma cihazı', 'filtre değişimi', 'su arıtma']::text[], 186),
  ('bicak-bileme', 'Bıçak bileme', 'Teknik Servis ve Onarım', NULL, ARRAY['bileyici', 'makas bileme', 'bıçakçı']::text[], 187),
  ('bilgisayar-magazasi', 'Bilgisayar mağazası', 'Bilişim ve Elektronik', 'bilisim-ve-teknoloji', ARRAY['bilgisayar', 'laptop', 'donanım', 'oyun bilgisayarı']::text[], 188),
  ('cep-telefonu-magazasi', 'Cep telefonu mağazası', 'Bilişim ve Elektronik', 'bilisim-ve-teknoloji', ARRAY['telefoncu', 'telefon aksesuarı', 'kılıf', 'ekran koruyucu']::text[], 189),
  ('elektronik-magazasi', 'Elektronik mağazası', 'Bilişim ve Elektronik', 'bilisim-ve-teknoloji', ARRAY['elektronik', 'televizyon', 'ses sistemi', 'kulaklık']::text[], 190),
  ('mobil-hat-ve-operator-bayii', 'Mobil hat ve operatör bayii', 'Bilişim ve Elektronik', 'bilisim-ve-teknoloji', ARRAY['hat', 'fatura', 'operatör', 'numara taşıma']::text[], 191),
  ('yazilim-firmasi', 'Yazılım firması', 'Bilişim ve Elektronik', 'bilisim-ve-teknoloji', ARRAY['yazılım', 'uygulama geliştirme', 'mobil uygulama']::text[], 192),
  ('web-tasarim', 'Web tasarım', 'Bilişim ve Elektronik', 'bilisim-ve-teknoloji', ARRAY['web sitesi', 'e-ticaret sitesi', 'seo', 'internet sitesi']::text[], 193),
  ('reklam-ve-dijital-ajans', 'Reklam ve dijital ajans', 'Bilişim ve Elektronik', 'bilisim-ve-teknoloji', ARRAY['sosyal medya ajansı', 'dijital pazarlama', 'reklam ajansı']::text[], 194),
  ('internet-kafe', 'İnternet kafe', 'Bilişim ve Elektronik', 'bilisim-ve-teknoloji', ARRAY['oyun kafe', 'ps kafe', 'playstation kafe', 'net kafe']::text[], 195),
  ('internet-servis-saglayici', 'İnternet servis sağlayıcı', 'Bilişim ve Elektronik', 'bilisim-ve-teknoloji', ARRAY['internet bağlantısı', 'fiber', 'modem', 'wifi']::text[], 196),
  ('ag-ve-kablolama', 'Ağ ve kablolama', 'Bilişim ve Elektronik', 'bilisim-ve-teknoloji', ARRAY['network', 'sunucu', 'bilgi işlem', 'kablolama']::text[], 197),
  ('veri-kurtarma', 'Veri kurtarma', 'Bilişim ve Elektronik', 'bilisim-ve-teknoloji', ARRAY['hard disk', 'silinen dosya', 'bozuk disk']::text[], 198),
  ('pos-ve-barkod-sistemleri', 'POS ve barkod sistemleri', 'Bilişim ve Elektronik', 'bilisim-ve-teknoloji', ARRAY['yazar kasa', 'pos cihazı', 'barkod', 'adisyon']::text[], 199),
  ('oyun-ve-konsol', 'Oyun ve konsol', 'Bilişim ve Elektronik', 'bilisim-ve-teknoloji', ARRAY['playstation', 'oyun satışı', 'konsol', 'xbox']::text[], 200),
  ('elektrikci', 'Elektrikçi', 'Usta ve Yapı Hizmetleri', 'tesisat', ARRAY['elektrik tesisatı', 'elektrik ustası', 'sigorta', 'priz']::text[], 201),
  ('su-tesisatcisi', 'Su tesisatçısı', 'Usta ve Yapı Hizmetleri', 'tesisat', ARRAY['tesisatçı', 'sıhhi tesisat', 'su kaçağı', 'musluk tamiri']::text[], 202),
  ('dogalgaz-tesisati', 'Doğalgaz tesisatı', 'Usta ve Yapı Hizmetleri', 'tesisat', ARRAY['doğalgaz projesi', 'gaz tesisatı', 'doğalgaz ustası']::text[], 203),
  ('tikaniklik-acma', 'Tıkanıklık açma', 'Usta ve Yapı Hizmetleri', 'tesisat', ARRAY['kanal açma', 'lavabo açma', 'logar', 'vidanjör', 'septik']::text[], 204),
  ('kaynakci-ve-demir-dograma', 'Kaynakçı ve demir doğrama', 'Usta ve Yapı Hizmetleri', 'kaynak-ustasi', ARRAY['kaynak', 'demir doğrama', 'ferforje', 'korkuluk']::text[], 205),
  ('boya-badana', 'Boya badana', 'Usta ve Yapı Hizmetleri', NULL, ARRAY['boyacı', 'badana', 'duvar kağıdı', 'iç cephe boya']::text[], 206),
  ('alci-ve-siva', 'Alçı ve sıva', 'Usta ve Yapı Hizmetleri', NULL, ARRAY['alçıpan', 'asma tavan', 'sıva ustası', 'kartonpiyer']::text[], 207),
  ('fayans-ve-seramik-ustasi', 'Fayans ve seramik ustası', 'Usta ve Yapı Hizmetleri', NULL, ARRAY['fayansçı', 'seramik döşeme', 'derz']::text[], 208),
  ('parke-ustasi', 'Parke ustası', 'Usta ve Yapı Hizmetleri', NULL, ARRAY['parke', 'laminat', 'parke cilası']::text[], 209),
  ('marangoz', 'Marangoz', 'Usta ve Yapı Hizmetleri', NULL, ARRAY['ahşap işleri', 'mobilya tamiri', 'doğramacı ahşap']::text[], 210),
  ('pvc-ve-aluminyum-dograma', 'PVC ve alüminyum doğrama', 'Usta ve Yapı Hizmetleri', NULL, ARRAY['pvc pencere', 'alüminyum doğrama', 'cam balkon', 'sineklik']::text[], 211),
  ('camci', 'Camcı', 'Usta ve Yapı Hizmetleri', NULL, ARRAY['cam kesimi', 'ayna', 'cam montajı']::text[], 212),
  ('cati-ustasi', 'Çatı ustası', 'Usta ve Yapı Hizmetleri', NULL, ARRAY['çatı tamiri', 'oluk', 'kiremit', 'çatı aktarma']::text[], 213),
  ('yalitim', 'Yalıtım', 'Usta ve Yapı Hizmetleri', NULL, ARRAY['ısı yalıtımı', 'mantolama', 'su yalıtımı', 'izolasyon']::text[], 214),
  ('insaat-firmasi', 'İnşaat firması', 'Usta ve Yapı Hizmetleri', NULL, ARRAY['müteahhit', 'yapı firması', 'inşaat']::text[], 215),
  ('tadilat-ve-dekorasyon', 'Tadilat ve dekorasyon', 'Usta ve Yapı Hizmetleri', NULL, ARRAY['tadilat', 'anahtar teslim', 'renovasyon', 'ev tamiri']::text[], 216),
  ('ic-mimar', 'İç mimar', 'Usta ve Yapı Hizmetleri', NULL, ARRAY['iç mimarlık', 'dekorasyon tasarımı']::text[], 217),
  ('mimarlik-ofisi', 'Mimarlık ofisi', 'Usta ve Yapı Hizmetleri', NULL, ARRAY['mimar', 'proje çizimi', 'ruhsat projesi']::text[], 218),
  ('muhendislik-burosu', 'Mühendislik bürosu', 'Usta ve Yapı Hizmetleri', NULL, ARRAY['statik proje', 'harita mühendisi', 'elektrik projesi']::text[], 219),
  ('cilingir', 'Çilingir', 'Usta ve Yapı Hizmetleri', NULL, ARRAY['kapı açma', 'kilit değişimi', 'anahtar kopyalama', 'anahtarcı']::text[], 220),
  ('mermerci', 'Mermerci', 'Usta ve Yapı Hizmetleri', NULL, ARRAY['mermer', 'granit', 'mezar taşı', 'mutfak tezgâhı']::text[], 221),
  ('tente-ve-pergola', 'Tente ve pergola', 'Usta ve Yapı Hizmetleri', NULL, ARRAY['tente', 'gölgelik', 'pergola', 'branda']::text[], 222),
  ('kepenk-ve-otomatik-kapi', 'Kepenk ve otomatik kapı', 'Usta ve Yapı Hizmetleri', NULL, ARRAY['kepenk', 'otomatik kapı', 'bariyer', 'garaj kapısı']::text[], 223),
  ('havuz-yapim-ve-bakim', 'Havuz yapım ve bakım', 'Usta ve Yapı Hizmetleri', NULL, ARRAY['havuz', 'havuz bakımı', 'havuz temizliği']::text[], 224),
  ('su-kuyusu-ve-sondaj', 'Su kuyusu ve sondaj', 'Usta ve Yapı Hizmetleri', NULL, ARRAY['sondaj', 'su kuyusu', 'kuyu açma']::text[], 225),
  ('mobilya-montaji', 'Mobilya montajı', 'Usta ve Yapı Hizmetleri', NULL, ARRAY['mobilya kurulumu', 'tv askı', 'montaj ustası']::text[], 226),
  ('hirdavat', 'Hırdavat', 'Yapı Malzemesi ve Hırdavat', NULL, ARRAY['nalbur', 'vida', 'el aleti', 'hırdavatçı']::text[], 227),
  ('yapi-market', 'Yapı market', 'Yapı Malzemesi ve Hırdavat', NULL, ARRAY['yapı malzemesi', 'bahçe malzemesi', 'dekorasyon market']::text[], 228),
  ('boya-bayii', 'Boya bayii', 'Yapı Malzemesi ve Hırdavat', NULL, ARRAY['boya satışı', 'boyacı dükkanı']::text[], 229),
  ('insaat-malzemesi', 'İnşaat malzemesi', 'Yapı Malzemesi ve Hırdavat', NULL, ARRAY['çimento', 'tuğla', 'kum', 'inşaat demiri', 'briket']::text[], 230),
  ('elektrik-malzemesi', 'Elektrik malzemesi', 'Yapı Malzemesi ve Hırdavat', NULL, ARRAY['kablo', 'anahtar priz', 'sigorta kutusu']::text[], 231),
  ('aydinlatma', 'Aydınlatma', 'Yapı Malzemesi ve Hırdavat', NULL, ARRAY['avize', 'lamba', 'led', 'aplik']::text[], 232),
  ('sihhi-tesisat-malzemesi', 'Sıhhi tesisat malzemesi', 'Yapı Malzemesi ve Hırdavat', NULL, ARRAY['musluk', 'batarya', 'boru', 'vana']::text[], 233),
  ('banyo-ve-seramik-magazasi', 'Banyo ve seramik mağazası', 'Yapı Malzemesi ve Hırdavat', NULL, ARRAY['vitrifiye', 'klozet', 'lavabo', 'duşakabin', 'seramik']::text[], 234),
  ('kereste-ve-ahsap', 'Kereste ve ahşap', 'Yapı Malzemesi ve Hırdavat', NULL, ARRAY['kereste', 'sunta', 'mdf', 'kontrplak']::text[], 235),
  ('kapi-satisi', 'Kapı satışı', 'Yapı Malzemesi ve Hırdavat', NULL, ARRAY['çelik kapı', 'iç kapı', 'amerikan kapı']::text[], 236),
  ('is-guvenligi-malzemesi', 'İş güvenliği malzemesi', 'Yapı Malzemesi ve Hırdavat', NULL, ARRAY['iş ayakkabısı', 'baret', 'eldiven', 'reflektif yelek']::text[], 237),
  ('ambalaj-malzemesi', 'Ambalaj malzemesi', 'Yapı Malzemesi ve Hırdavat', NULL, ARRAY['koli', 'poşet', 'ambalaj', 'streç film']::text[], 238),
  ('mobilya-magazasi', 'Mobilya mağazası', 'Mobilya ve Ev Eşyası', NULL, ARRAY['koltuk takımı', 'yatak odası', 'yemek odası', 'mobilyacı']::text[], 239),
  ('yatak-ve-baza', 'Yatak ve baza', 'Mobilya ve Ev Eşyası', NULL, ARRAY['yatak', 'baza', 'başlık', 'ortopedik yatak']::text[], 240),
  ('hali-magazasi', 'Halı mağazası', 'Mobilya ve Ev Eşyası', NULL, ARRAY['halı', 'kilim', 'yolluk', 'halıcı']::text[], 241),
  ('perdeci', 'Perdeci', 'Mobilya ve Ev Eşyası', NULL, ARRAY['perde', 'stor', 'jaluzi', 'tül', 'zebra perde']::text[], 242),
  ('ev-tekstili-ve-ceyiz', 'Ev tekstili ve çeyiz', 'Mobilya ve Ev Eşyası', NULL, ARRAY['nevresim', 'havlu', 'çeyiz', 'pike', 'battaniye']::text[], 243),
  ('zuccaciye', 'Züccaciye', 'Mobilya ve Ev Eşyası', NULL, ARRAY['tabak', 'bardak', 'mutfak eşyası', 'tencere', 'plastik ürünler']::text[], 244),
  ('beyaz-esya-magazasi', 'Beyaz eşya mağazası', 'Mobilya ve Ev Eşyası', NULL, ARRAY['buzdolabı', 'çamaşır makinesi', 'ankastre fırın', 'bulaşık makinesi']::text[], 245),
  ('kucuk-ev-aletleri', 'Küçük ev aletleri', 'Mobilya ve Ev Eşyası', NULL, ARRAY['süpürge', 'kahve makinesi', 'blender', 'ütü', 'airfryer']::text[], 246),
  ('mutfak-ve-dolap-imalati', 'Mutfak ve dolap imalatı', 'Mobilya ve Ev Eşyası', NULL, ARRAY['mutfak dolabı', 'gardırop', 'vestiyer', 'banyo dolabı']::text[], 247),
  ('ofis-mobilyasi', 'Ofis mobilyası', 'Mobilya ve Ev Eşyası', NULL, ARRAY['büro mobilyası', 'ofis koltuğu', 'çalışma masası']::text[], 248),
  ('bahce-mobilyasi', 'Bahçe mobilyası', 'Mobilya ve Ev Eşyası', NULL, ARRAY['bahçe takımı', 'hamak', 'şezlong', 'salıncak']::text[], 249),
  ('ev-dekorasyonu', 'Ev dekorasyonu', 'Mobilya ve Ev Eşyası', NULL, ARRAY['dekoratif ürünler', 'tablo', 'vazo', 'ayna']::text[], 250),
  ('ikinci-el-esya', 'İkinci el eşya', 'Mobilya ve Ev Eşyası', NULL, ARRAY['spotçu', 'ikinci el mobilya', 'eşya alım satım']::text[], 251),
  ('antikaci', 'Antikacı', 'Mobilya ve Ev Eşyası', NULL, ARRAY['antika', 'eski eşya', 'koleksiyon']::text[], 252),
  ('cerceveci', 'Çerçeveci', 'Mobilya ve Ev Eşyası', NULL, ARRAY['çerçeve', 'kanvas tablo', 'poster']::text[], 253),
  ('soba-ve-isitici', 'Soba ve ısıtıcı', 'Mobilya ve Ev Eşyası', NULL, ARRAY['soba', 'ısıtıcı', 'şömine', 'elektrikli ısıtıcı']::text[], 254),
  ('dosemeci', 'Döşemeci', 'Mobilya ve Ev Eşyası', NULL, ARRAY['koltuk döşeme', 'kanepe yenileme', 'sandalye kaplama']::text[], 255),
  ('bakirci-ve-kalayci', 'Bakırcı ve kalaycı', 'Mobilya ve Ev Eşyası', NULL, ARRAY['bakır', 'kalay', 'bakır eşya']::text[], 256),
  ('ev-temizligi', 'Ev temizliği', 'Temizlik', NULL, ARRAY['temizlikçi', 'gündelikçi', 'ev temizlik hizmeti']::text[], 257),
  ('temizlik-sirketi', 'Temizlik şirketi', 'Temizlik', NULL, ARRAY['ofis temizliği', 'bina temizliği', 'inşaat sonrası temizlik']::text[], 258),
  ('hali-yikama', 'Halı yıkama', 'Temizlik', NULL, ARRAY['halı yıkama fabrikası', 'kilim yıkama']::text[], 259),
  ('koltuk-ve-yatak-yikama', 'Koltuk ve yatak yıkama', 'Temizlik', NULL, ARRAY['koltuk yıkama', 'yatak yıkama', 'yerinde yıkama']::text[], 260),
  ('kuru-temizleme', 'Kuru temizleme', 'Temizlik', NULL, ARRAY['kuru temizlemeci', 'ütü hizmeti']::text[], 261),
  ('camasirhane', 'Çamaşırhane', 'Temizlik', NULL, ARRAY['çamaşır yıkama', 'self servis çamaşır', 'laundry']::text[], 262),
  ('ilaclama', 'İlaçlama', 'Temizlik', NULL, ARRAY['böcek ilaçlama', 'haşere', 'fare', 'dezenfeksiyon']::text[], 263),
  ('dis-cephe-ve-cam-temizligi', 'Dış cephe ve cam temizliği', 'Temizlik', NULL, ARRAY['cephe yıkama', 'cam silme', 'yüksek cam']::text[], 264),
  ('baca-temizligi', 'Baca temizliği', 'Temizlik', NULL, ARRAY['baca', 'soba borusu temizliği']::text[], 265),
  ('evden-eve-nakliyat', 'Evden eve nakliyat', 'Nakliye ve Taşımacılık', 'nakliye', ARRAY['ev taşıma', 'asansörlü taşıma', 'ofis taşıma', 'nakliyeci']::text[], 266),
  ('sehir-ici-nakliye', 'Şehir içi nakliye', 'Nakliye ve Taşımacılık', 'nakliye', ARRAY['kamyonet', 'yük taşıma', 'parça eşya taşıma']::text[], 267),
  ('sehirlerarasi-nakliye', 'Şehirlerarası nakliye', 'Nakliye ve Taşımacılık', 'nakliye', ARRAY['parsiyel', 'ambar', 'şehirlerarası taşıma']::text[], 268),
  ('kurye', 'Kurye', 'Nakliye ve Taşımacılık', 'nakliye', ARRAY['moto kurye', 'acil kurye', 'paket teslimat']::text[], 269),
  ('kargo-subesi', 'Kargo şubesi', 'Nakliye ve Taşımacılık', 'nakliye', ARRAY['kargo', 'gönderi', 'paket gönderme']::text[], 270),
  ('depolama', 'Depolama', 'Nakliye ve Taşımacılık', 'nakliye', ARRAY['eşya depolama', 'depo', 'antrepo', 'lojistik']::text[], 271),
  ('vinc-ve-platform-kiralama', 'Vinç ve platform kiralama', 'Nakliye ve Taşımacılık', 'nakliye', ARRAY['vinç', 'sepetli platform', 'forklift']::text[], 272),
  ('hafriyat-ve-is-makinesi', 'Hafriyat ve iş makinesi', 'Nakliye ve Taşımacılık', 'nakliye', ARRAY['kazı', 'hafriyat', 'kepçe', 'iş makinesi kiralama']::text[], 273),
  ('hayvan-nakliyesi', 'Hayvan nakliyesi', 'Nakliye ve Taşımacılık', 'nakliye', ARRAY['hayvan taşıma', 'canlı hayvan nakliye']::text[], 274),
  ('taksi-duragi', 'Taksi durağı', 'Ulaşım ve Seyahat', NULL, ARRAY['taksi', 'taksi çağır']::text[], 275),
  ('servis-ve-transfer', 'Servis ve transfer', 'Ulaşım ve Seyahat', NULL, ARRAY['personel servisi', 'okul servisi', 'havalimanı transferi', 'vip transfer']::text[], 276),
  ('otobus-firmasi', 'Otobüs firması', 'Ulaşım ve Seyahat', NULL, ARRAY['şehirlerarası otobüs', 'otobüs bileti', 'yazıhane']::text[], 277),
  ('seyahat-acentesi', 'Seyahat acentesi', 'Ulaşım ve Seyahat', NULL, ARRAY['tur', 'uçak bileti', 'otel rezervasyonu', 'turizm']::text[], 278),
  ('hac-ve-umre', 'Hac ve umre', 'Ulaşım ve Seyahat', NULL, ARRAY['umre turu', 'hac organizasyonu']::text[], 279),
  ('arac-kiralama', 'Araç kiralama', 'Ulaşım ve Seyahat', NULL, ARRAY['rent a car', 'oto kiralama', 'kiralık araba']::text[], 280),
  ('otel', 'Otel', 'Konaklama', NULL, ARRAY['butik otel', 'konaklama', 'oda']::text[], 281),
  ('pansiyon', 'Pansiyon', 'Konaklama', NULL, ARRAY['misafirhane', 'öğretmenevi', 'ev pansiyonu']::text[], 282),
  ('apart-ve-gunluk-kiralik', 'Apart ve günlük kiralık', 'Konaklama', NULL, ARRAY['apart daire', 'günlük kiralık ev', 'apart otel']::text[], 283),
  ('bungalov-ve-kamp', 'Bungalov ve kamp', 'Konaklama', NULL, ARRAY['bungalov', 'kamp alanı', 'glamping', 'karavan']::text[], 284),
  ('ogrenci-yurdu', 'Öğrenci yurdu', 'Konaklama', NULL, ARRAY['yurt', 'kız yurdu', 'erkek yurdu', 'öğrenci evi']::text[], 285),
  ('termal-otel', 'Termal otel', 'Konaklama', NULL, ARRAY['kaplıca', 'termal', 'ılıca']::text[], 286),
  ('etut-ve-kurs-merkezi', 'Etüt ve kurs merkezi', 'Eğitim', NULL, ARRAY['dershane', 'etüt', 'lgs', 'yks', 'kpss kursu']::text[], 287),
  ('ozel-ders', 'Özel ders', 'Eğitim', NULL, ARRAY['birebir ders', 'öğretmen', 'matematik dersi']::text[], 288),
  ('yabanci-dil-kursu', 'Yabancı dil kursu', 'Eğitim', NULL, ARRAY['ingilizce', 'almanca', 'arapça', 'dil okulu']::text[], 289),
  ('surucu-kursu', 'Sürücü kursu', 'Eğitim', NULL, ARRAY['ehliyet', 'direksiyon dersi', 'sürücü okulu']::text[], 290),
  ('anaokulu-ve-kres', 'Anaokulu ve kreş', 'Eğitim', NULL, ARRAY['kreş', 'gündüz bakımevi', 'oyun grubu']::text[], 291),
  ('ozel-okul', 'Özel okul', 'Eğitim', NULL, ARRAY['kolej', 'ilkokul', 'ortaokul', 'lise']::text[], 292),
  ('muzik-kursu', 'Müzik kursu', 'Eğitim', NULL, ARRAY['gitar dersi', 'piyano', 'bağlama kursu', 'keman']::text[], 293),
  ('dans-kursu', 'Dans kursu', 'Eğitim', NULL, ARRAY['dans okulu', 'salsa', 'halk oyunları', 'bale']::text[], 294),
  ('sanat-ve-hobi-atolyesi', 'Sanat ve hobi atölyesi', 'Eğitim', NULL, ARRAY['resim kursu', 'seramik atölyesi', 'el sanatları kursu']::text[], 295),
  ('kodlama-ve-robotik-kursu', 'Kodlama ve robotik kursu', 'Eğitim', NULL, ARRAY['bilgisayar kursu', 'yazılım kursu', 'robotik kodlama']::text[], 296),
  ('ozel-egitim-merkezi', 'Özel eğitim merkezi', 'Eğitim', NULL, ARRAY['rehabilitasyon merkezi', 'otizm', 'özel gereksinim']::text[], 297),
  ('meslek-kursu', 'Meslek kursu', 'Eğitim', NULL, ARRAY['aşçılık kursu', 'kuaförlük kursu', 'sertifika programı']::text[], 298),
  ('kuran-kursu', 'Kuran kursu', 'Eğitim', NULL, ARRAY['hafızlık', 'kuran', 'tecvit']::text[], 299),
  ('egitim-danismanligi', 'Eğitim danışmanlığı', 'Eğitim', NULL, ARRAY['yurt dışı eğitim', 'üniversite danışmanlığı']::text[], 300),
  ('cocuk-oyun-alani', 'Çocuk oyun alanı', 'Eğlence ve Etkinlik', 'eglence', ARRAY['oyun parkı', 'top havuzu', 'oyun evi']::text[], 301),
  ('dogum-gunu-organizasyonu', 'Doğum günü organizasyonu', 'Eğlence ve Etkinlik', 'eglence', ARRAY['çocuk partisi', 'animatör', 'palyaço', 'parti']::text[], 302),
  ('organizasyon-firmasi', 'Organizasyon firması', 'Eğlence ve Etkinlik', 'eglence', ARRAY['etkinlik organizasyonu', 'açılış organizasyonu', 'lansman']::text[], 303),
  ('sinema', 'Sinema', 'Eğlence ve Etkinlik', 'eglence', ARRAY['film', 'sinema salonu']::text[], 304),
  ('tiyatro-ve-gosteri', 'Tiyatro ve gösteri', 'Eğlence ve Etkinlik', 'eglence', ARRAY['tiyatro', 'gösteri', 'stand up']::text[], 305),
  ('konser-ve-canli-muzik-mekani', 'Konser ve canlı müzik mekânı', 'Eğlence ve Etkinlik', 'eglence', ARRAY['canlı müzik', 'sahne', 'konser salonu']::text[], 306),
  ('gece-kulubu', 'Gece kulübü', 'Eğlence ve Etkinlik', 'eglence', ARRAY['kulüp', 'disko', 'gece hayatı']::text[], 307),
  ('bilardo-salonu', 'Bilardo salonu', 'Eğlence ve Etkinlik', 'eglence', ARRAY['bilardo', 'bilardo kafe']::text[], 308),
  ('bowling', 'Bowling', 'Eğlence ve Etkinlik', 'eglence', ARRAY['bowling salonu']::text[], 309),
  ('kacis-oyunu', 'Kaçış oyunu', 'Eğlence ve Etkinlik', 'eglence', ARRAY['escape room', 'kaçış odası']::text[], 310),
  ('paintball-ve-airsoft', 'Paintball ve airsoft', 'Eğlence ve Etkinlik', 'eglence', ARRAY['paintball', 'airsoft']::text[], 311),
  ('lunapark', 'Lunapark', 'Eğlence ve Etkinlik', 'eglence', ARRAY['eğlence parkı', 'luna park']::text[], 312),
  ('karaoke', 'Karaoke', 'Eğlence ve Etkinlik', 'eglence', ARRAY['karaoke bar']::text[], 313),
  ('oyun-salonu', 'Oyun salonu', 'Eğlence ve Etkinlik', 'eglence', ARRAY['atari salonu', 'oyun makineleri']::text[], 314),
  ('piknik-ve-mesire-alani', 'Piknik ve mesire alanı', 'Eğlence ve Etkinlik', 'eglence', ARRAY['mesire yeri', 'piknik alanı', 'kır bahçesi']::text[], 315),
  ('muzisyen-ve-orkestra', 'Müzisyen ve orkestra', 'Eğlence ve Etkinlik', 'eglence', ARRAY['düğün orkestrası', 'dj', 'davul zurna', 'müzik grubu']::text[], 316),
  ('ses-ve-sahne-kiralama', 'Ses ve sahne kiralama', 'Eğlence ve Etkinlik', 'eglence', ARRAY['ses sistemi kiralama', 'sahne kiralama', 'ışık sistemi']::text[], 317),
  ('balon-ve-parti-susleme', 'Balon ve parti süsleme', 'Eğlence ve Etkinlik', 'eglence', ARRAY['balon süsleme', 'parti malzemeleri', 'konsept süsleme']::text[], 318),
  ('dugun-salonu', 'Düğün salonu', 'Düğün ve Özel Gün', 'eglence', ARRAY['düğün', 'nikah salonu', 'kır düğünü mekânı']::text[], 319),
  ('dugun-organizasyonu', 'Düğün organizasyonu', 'Düğün ve Özel Gün', 'eglence', ARRAY['kına organizasyonu', 'nişan organizasyonu', 'söz organizasyonu']::text[], 320),
  ('gelinlik', 'Gelinlik', 'Düğün ve Özel Gün', 'giyim', ARRAY['gelinlikçi', 'gelinlik kiralama']::text[], 321),
  ('davetiye-ve-nikah-sekeri', 'Davetiye ve nikah şekeri', 'Düğün ve Özel Gün', 'eglence', ARRAY['davetiye', 'nikah şekeri', 'söz çikolatası']::text[], 322),
  ('sunnet-organizasyonu', 'Sünnet organizasyonu', 'Düğün ve Özel Gün', 'eglence', ARRAY['sünnet düğünü', 'sünnet kıyafeti']::text[], 323),
  ('cicekci', 'Çiçekçi', 'Düğün ve Özel Gün', NULL, ARRAY['çiçek', 'buket', 'çelenk', 'saksı çiçeği', 'gelin arabası süsleme']::text[], 324),
  ('fotografci', 'Fotoğrafçı', 'Fotoğraf ve Video', NULL, ARRAY['fotoğraf stüdyosu', 'vesikalık', 'düğün fotoğrafçısı']::text[], 325),
  ('video-cekimi', 'Video çekimi', 'Fotoğraf ve Video', NULL, ARRAY['kameraman', 'drone çekimi', 'klip çekimi']::text[], 326),
  ('fotograf-baski', 'Fotoğraf baskı', 'Fotoğraf ve Video', NULL, ARRAY['fotoğraf tab', 'albüm', 'fotoğraf basımı']::text[], 327),
  ('spor-salonu', 'Spor salonu', 'Spor ve Hobi', NULL, ARRAY['fitness', 'gym', 'vücut geliştirme', 'spor merkezi']::text[], 328),
  ('pilates-ve-yoga', 'Pilates ve yoga', 'Spor ve Hobi', NULL, ARRAY['pilates', 'yoga', 'reformer pilates']::text[], 329),
  ('dovus-sporlari', 'Dövüş sporları', 'Spor ve Hobi', NULL, ARRAY['boks', 'kick boks', 'karate', 'tekvando', 'muay thai']::text[], 330),
  ('yuzme-havuzu', 'Yüzme havuzu', 'Spor ve Hobi', NULL, ARRAY['yüzme kursu', 'havuz', 'kapalı havuz']::text[], 331),
  ('hali-saha', 'Halı saha', 'Spor ve Hobi', 'eglence', ARRAY['futbol sahası', 'maç', 'halısaha']::text[], 332),
  ('tenis-kortu', 'Tenis kortu', 'Spor ve Hobi', NULL, ARRAY['tenis', 'tenis kulübü', 'padel']::text[], 333),
  ('futbol-okulu', 'Futbol okulu', 'Spor ve Hobi', NULL, ARRAY['futbol akademisi', 'çocuk futbolu']::text[], 334),
  ('kisisel-antrenor', 'Kişisel antrenör', 'Spor ve Hobi', NULL, ARRAY['personal trainer', 'pt', 'özel antrenör']::text[], 335),
  ('binicilik', 'Binicilik', 'Spor ve Hobi', NULL, ARRAY['at binme', 'binicilik kulübü', 'pony']::text[], 336),
  ('spor-malzemeleri', 'Spor malzemeleri', 'Spor ve Hobi', NULL, ARRAY['spor mağazası', 'forma', 'top', 'fitness ekipmanı']::text[], 337),
  ('bisikletci', 'Bisikletçi', 'Spor ve Hobi', NULL, ARRAY['bisiklet', 'bisiklet tamiri', 'elektrikli bisiklet']::text[], 338),
  ('av-ve-balikcilik-malzemeleri', 'Av ve balıkçılık malzemeleri', 'Spor ve Hobi', NULL, ARRAY['avcılık', 'olta', 'av tüfeği', 'balıkçılık']::text[], 339),
  ('kamp-ve-outdoor', 'Kamp ve outdoor', 'Spor ve Hobi', NULL, ARRAY['çadır', 'kamp ekipmanı', 'uyku tulumu']::text[], 340),
  ('muzik-aleti-magazasi', 'Müzik aleti mağazası', 'Spor ve Hobi', NULL, ARRAY['enstrüman', 'gitar', 'bağlama', 'saz', 'müzik market']::text[], 341),
  ('hobi-malzemeleri', 'Hobi malzemeleri', 'Spor ve Hobi', NULL, ARRAY['maket', 'boncuk', 'el işi', 'örgü ipi']::text[], 342),
  ('veteriner', 'Veteriner', 'Evcil Hayvan ve Hayvancılık', 'hayvancilik', ARRAY['veteriner kliniği', 'hayvan hastanesi', 'veteriner hekim']::text[], 343),
  ('pet-shop', 'Pet shop', 'Evcil Hayvan ve Hayvancılık', 'hayvancilik', ARRAY['petshop', 'mama', 'kedi maması', 'köpek maması', 'evcil hayvan']::text[], 344),
  ('hayvan-kuaforu', 'Hayvan kuaförü', 'Evcil Hayvan ve Hayvancılık', 'hayvancilik', ARRAY['pet kuaför', 'köpek tıraşı', 'kedi tıraşı']::text[], 345),
  ('hayvan-oteli', 'Hayvan oteli', 'Evcil Hayvan ve Hayvancılık', 'hayvancilik', ARRAY['pet otel', 'köpek pansiyonu', 'kedi oteli']::text[], 346),
  ('kopek-egitimi', 'Köpek eğitimi', 'Evcil Hayvan ve Hayvancılık', 'hayvancilik', ARRAY['köpek eğitmeni', 'köpek okulu']::text[], 347),
  ('akvaryumcu', 'Akvaryumcu', 'Evcil Hayvan ve Hayvancılık', 'hayvancilik', ARRAY['akvaryum', 'süs balığı', 'balık yemi']::text[], 348),
  ('kuscu', 'Kuşçu', 'Evcil Hayvan ve Hayvancılık', 'hayvancilik', ARRAY['muhabbet kuşu', 'kanarya', 'güvercin', 'kuş yemi']::text[], 349),
  ('yem-bayii', 'Yem bayii', 'Evcil Hayvan ve Hayvancılık', 'hayvancilik', ARRAY['yem', 'saman', 'küspe', 'hayvan yemi']::text[], 350),
  ('besicilik-ve-canli-hayvan', 'Besicilik ve canlı hayvan', 'Evcil Hayvan ve Hayvancılık', 'hayvancilik', ARRAY['besi çiftliği', 'büyükbaş', 'küçükbaş', 'dana', 'koyun']::text[], 351),
  ('kurbanlik-satisi', 'Kurbanlık satışı', 'Evcil Hayvan ve Hayvancılık', 'hayvancilik', ARRAY['kurbanlık', 'kurban kesimi', 'adak']::text[], 352),
  ('kanatli-ciftligi', 'Kanatlı çiftliği', 'Evcil Hayvan ve Hayvancılık', 'hayvancilik', ARRAY['tavuk çiftliği', 'hindi', 'kaz', 'ördek', 'yumurta tavuğu']::text[], 353),
  ('sut-ciftligi', 'Süt çiftliği', 'Evcil Hayvan ve Hayvancılık', 'hayvancilik', ARRAY['inek', 'süt sığırı', 'süt üretimi']::text[], 354),
  ('aricilik', 'Arıcılık', 'Evcil Hayvan ve Hayvancılık', 'hayvancilik', ARRAY['arıcı', 'kovan', 'ana arı']::text[], 355),
  ('veteriner-ilac-ve-malzeme', 'Veteriner ilaç ve malzeme', 'Evcil Hayvan ve Hayvancılık', 'hayvancilik', ARRAY['veteriner ecza', 'hayvan ilacı', 'aşı']::text[], 356),
  ('zirai-ilac-gubre-ve-tohum', 'Zirai ilaç, gübre ve tohum', 'Tarım ve Bahçe', NULL, ARRAY['zirai ilaç', 'gübre', 'tohum', 'tarım ilaçları']::text[], 357),
  ('fidanlik', 'Fidanlık', 'Tarım ve Bahçe', NULL, ARRAY['fidan', 'fide', 'çiçek fidesi', 'saksı', 'toprak']::text[], 358),
  ('peyzaj-ve-bahce-bakimi', 'Peyzaj ve bahçe bakımı', 'Tarım ve Bahçe', NULL, ARRAY['bahçıvan', 'çim', 'ağaç budama', 'peyzaj']::text[], 359),
  ('tarim-makineleri', 'Tarım makineleri', 'Tarım ve Bahçe', NULL, ARRAY['traktör', 'pulluk', 'tarım aletleri', 'biçerdöver']::text[], 360),
  ('sulama-sistemleri', 'Sulama sistemleri', 'Tarım ve Bahçe', NULL, ARRAY['damla sulama', 'dalgıç pompa', 'sulama']::text[], 361),
  ('seracilik', 'Seracılık', 'Tarım ve Bahçe', NULL, ARRAY['sera', 'sera malzemesi', 'sera naylonu']::text[], 362),
  ('hububat-tuccari', 'Hububat tüccarı', 'Tarım ve Bahçe', NULL, ARRAY['tahıl', 'buğday alımı', 'arpa', 'mısır']::text[], 363),
  ('kirtasiye', 'Kırtasiye', 'Kırtasiye, Kitap ve Hediye', NULL, ARRAY['kalem', 'defter', 'okul malzemesi', 'kırtasiyeci']::text[], 364),
  ('kitabevi', 'Kitabevi', 'Kırtasiye, Kitap ve Hediye', NULL, ARRAY['kitap', 'kitapçı', 'test kitabı']::text[], 365),
  ('fotokopi-ve-baski-merkezi', 'Fotokopi ve baskı merkezi', 'Kırtasiye, Kitap ve Hediye', NULL, ARRAY['fotokopi', 'çıktı', 'ciltleme', 'tarama']::text[], 366),
  ('matbaa', 'Matbaa', 'Kırtasiye, Kitap ve Hediye', NULL, ARRAY['kartvizit', 'broşür', 'afiş', 'el ilanı', 'basım']::text[], 367),
  ('reklam-tabela', 'Reklam tabela', 'Kırtasiye, Kitap ve Hediye', NULL, ARRAY['tabela', 'totem', 'kutu harf', 'dijital baskı', 'branda baskı']::text[], 368),
  ('hediyelik-esya', 'Hediyelik eşya', 'Kırtasiye, Kitap ve Hediye', NULL, ARRAY['hediye', 'hediyelik', 'kişiye özel hediye']::text[], 369),
  ('el-sanatlari', 'El sanatları', 'Kırtasiye, Kitap ve Hediye', NULL, ARRAY['el emeği', 'örgü', 'dantel', 'yöresel el sanatları']::text[], 370),
  ('oyuncakci', 'Oyuncakçı', 'Kırtasiye, Kitap ve Hediye', NULL, ARRAY['oyuncak', 'çocuk oyuncağı', 'puzzle']::text[], 371),
  ('kupa-ve-plaket', 'Kupa ve plaket', 'Kırtasiye, Kitap ve Hediye', NULL, ARRAY['ödül', 'madalya', 'plaket', 'kupa']::text[], 372),
  ('gazete-bayii', 'Gazete bayii', 'Kırtasiye, Kitap ve Hediye', NULL, ARRAY['gazete', 'dergi', 'bayi']::text[], 373),
  ('kase-ve-muhur', 'Kaşe ve mühür', 'Kırtasiye, Kitap ve Hediye', NULL, ARRAY['kaşe', 'mühür', 'ıslak imza kaşesi']::text[], 374),
  ('dini-urunler', 'Dini ürünler', 'Kırtasiye, Kitap ve Hediye', NULL, ARRAY['tespih', 'seccade', 'dini yayın', 'takke']::text[], 375),
  ('avukat', 'Avukat', 'Mesleki Hizmetler', NULL, ARRAY['hukuk bürosu', 'dava', 'hukuki danışmanlık', 'avukatlık']::text[], 376),
  ('mali-musavir', 'Mali müşavir', 'Mesleki Hizmetler', NULL, ARRAY['muhasebe', 'muhasebeci', 'vergi', 'smmm']::text[], 377),
  ('noter', 'Noter', 'Mesleki Hizmetler', NULL, ARRAY['noterlik', 'noter onayı']::text[], 378),
  ('tercume-burosu', 'Tercüme bürosu', 'Mesleki Hizmetler', NULL, ARRAY['çeviri', 'yeminli tercüman', 'tercüman']::text[], 379),
  ('isletme-danismanligi', 'İşletme danışmanlığı', 'Mesleki Hizmetler', NULL, ARRAY['danışmanlık firması', 'kurumsal danışmanlık']::text[], 380),
  ('insan-kaynaklari', 'İnsan kaynakları', 'Mesleki Hizmetler', NULL, ARRAY['iş bulma', 'personel temini', 'eleman']::text[], 381),
  ('gumruk-musaviri', 'Gümrük müşaviri', 'Mesleki Hizmetler', NULL, ARRAY['gümrük', 'ithalat', 'ihracat']::text[], 382),
  ('vize-danismanligi', 'Vize danışmanlığı', 'Mesleki Hizmetler', NULL, ARRAY['vize', 'pasaport işlemleri']::text[], 383),
  ('is-sagligi-ve-guvenligi', 'İş sağlığı ve güvenliği', 'Mesleki Hizmetler', NULL, ARRAY['isg', 'iş güvenliği uzmanı', 'osgb']::text[], 384),
  ('marka-ve-patent-tescil', 'Marka ve patent tescil', 'Mesleki Hizmetler', NULL, ARRAY['marka tescili', 'patent']::text[], 385),
  ('arzuhalci', 'Arzuhalci', 'Mesleki Hizmetler', NULL, ARRAY['dilekçe yazımı', 'e-devlet işlemleri']::text[], 386),
  ('ozel-guvenlik', 'Özel güvenlik', 'Mesleki Hizmetler', NULL, ARRAY['güvenlik görevlisi', 'koruma']::text[], 387),
  ('cenaze-hizmetleri', 'Cenaze hizmetleri', 'Mesleki Hizmetler', NULL, ARRAY['cenaze', 'cenaze nakil', 'mezar yapımı']::text[], 388),
  ('bakici-hizmeti', 'Bakıcı hizmeti', 'Mesleki Hizmetler', NULL, ARRAY['çocuk bakıcısı', 'yaşlı bakıcısı', 'dadı', 'hasta bakıcı']::text[], 389),
  ('emlakci', 'Emlakçı', 'Emlak, Finans ve Sigorta', NULL, ARRAY['emlak ofisi', 'kiralık ev', 'satılık ev', 'gayrimenkul']::text[], 390),
  ('gayrimenkul-degerleme', 'Gayrimenkul değerleme', 'Emlak, Finans ve Sigorta', NULL, ARRAY['değerleme', 'gayrimenkul ekspertizi']::text[], 391),
  ('site-ve-apartman-yonetimi', 'Site ve apartman yönetimi', 'Emlak, Finans ve Sigorta', NULL, ARRAY['apartman yönetimi', 'bina yönetimi', 'site yönetimi']::text[], 392),
  ('sigorta-acentesi', 'Sigorta acentesi', 'Emlak, Finans ve Sigorta', NULL, ARRAY['kasko', 'trafik sigortası', 'sağlık sigortası', 'dask']::text[], 393),
  ('doviz-burosu', 'Döviz bürosu', 'Emlak, Finans ve Sigorta', NULL, ARRAY['döviz', 'altın alım satım', 'kambiyo']::text[], 394),
  ('banka-subesi', 'Banka şubesi', 'Emlak, Finans ve Sigorta', NULL, ARRAY['banka', 'atm']::text[], 395),
  ('fatura-odeme-merkezi', 'Fatura ödeme merkezi', 'Emlak, Finans ve Sigorta', NULL, ARRAY['fatura ödeme', 'tl yükleme', 'ödeme noktası']::text[], 396),
  ('akaryakit-istasyonu', 'Akaryakıt istasyonu', 'Enerji ve Yakıt', NULL, ARRAY['benzinlik', 'petrol', 'mazot', 'benzin']::text[], 397),
  ('tup-bayii', 'Tüp bayii', 'Enerji ve Yakıt', NULL, ARRAY['lpg tüp', 'mutfak tüpü', 'piknik tüpü', 'tüpçü']::text[], 398),
  ('odun-ve-komur', 'Odun ve kömür', 'Enerji ve Yakıt', NULL, ARRAY['kömürcü', 'odun', 'pelet', 'yakacak']::text[], 399),
  ('gunes-enerjisi', 'Güneş enerjisi', 'Enerji ve Yakıt', NULL, ARRAY['güneş paneli', 'solar panel', 'ges', 'güneş enerjisi sistemi']::text[], 400),
  ('elektrikli-arac-sarj', 'Elektrikli araç şarj', 'Enerji ve Yakıt', NULL, ARRAY['şarj istasyonu', 'elektrikli araç']::text[], 401)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  group_name = EXCLUDED.group_name,
  sector_slug = EXCLUDED.sector_slug,
  synonyms = EXCLUDED.synonyms,
  position = EXCLUDED.position,
  is_active = true,
  updated_at = now();
