// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";
import { getPublicSupabaseEnv } from "@/lib/public-env";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get("Authorization") === `Bearer ${supabaseKey}`) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

const unavailable = {
  message: "Supabase ortam değişkenleri eksik.",
  code: "MISSING_ENV",
};

function unavailableResult<T>(data: T) {
  const payload = { data, error: unavailable, count: null, status: 400, statusText: "Bad Request" };
  return Object.assign(Promise.resolve(payload), payload);
}

function chainableQuery() {
  const builder: Record<string, unknown> = {};
  const get = (_: unknown, prop: string | symbol) => {
    if (prop === "then") {
      return (onFulfilled?: (value: unknown) => unknown, onRejected?: (reason: unknown) => unknown) =>
        unavailableResult(null).then(onFulfilled, onRejected);
    }
    if (prop === "maybeSingle" || prop === "single" || prop === "throwOnError") {
      return () => unavailableResult(null);
    }
    return (..._args: unknown[]) => new Proxy(builder, { get });
  };
  return new Proxy(builder, { get });
}

function createUnavailableClient(): SupabaseClient<Database> {
  const auth = {
    getSession: async () => ({ data: { session: null }, error: null }),
    getUser: async () => ({ data: { user: null }, error: null }),
    onAuthStateChange: () => ({
      data: { subscription: { id: "noop", unsubscribe() {} } },
      error: null,
    }),
    signOut: async () => ({ error: null }),
    signInWithPassword: async () => ({
      data: { user: null, session: null },
      error: unavailable,
    }),
    signUp: async () => ({ data: { user: null, session: null }, error: unavailable }),
    signInWithOtp: async () => ({ data: { user: null, session: null }, error: unavailable }),
    verifyOtp: async () => ({ data: { user: null, session: null }, error: unavailable }),
    resetPasswordForEmail: async () => ({ data: {}, error: unavailable }),
    updateUser: async () => ({ data: { user: null }, error: unavailable }),
  };

  const channel = () => {
    const ch = {
      on: () => ch,
      subscribe: () => "CLOSED" as const,
      unsubscribe: async () => "ok" as const,
    };
    return ch;
  };

  return new Proxy(
    { auth, from: () => chainableQuery(), channel, removeChannel: () => undefined },
    {
      get(target, prop, receiver) {
        if (prop in target) return Reflect.get(target, prop, receiver);
        if (prop === "then") return undefined;
        return () => chainableQuery();
      },
    },
  ) as unknown as SupabaseClient<Database>;
}

function createSupabaseClient(): SupabaseClient<Database> {
  const { VITE_SUPABASE_URL: SUPABASE_URL, VITE_SUPABASE_PUBLISHABLE_KEY: SUPABASE_PUBLISHABLE_KEY } =
    getPublicSupabaseEnv();

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.error(
      "[Supabase] Missing Supabase environment variable(s): SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY. Connect Supabase in Lovable Cloud.",
    );
    return createUnavailableClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: SupabaseClient<Database> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(_, prop, receiver) {
    try {
      if (!_supabase) _supabase = createSupabaseClient();
      return Reflect.get(_supabase, prop, receiver);
    } catch (error) {
      console.error("[Supabase] İstemci başlatılamadı", error);
      _supabase = createUnavailableClient();
      return Reflect.get(_supabase, prop, receiver);
    }
  },
});
